### PR TITLE
Add "abort" methods to Assumptions

### PR DESCRIPTION
**Pull request by ZeroOne3010**
## Overview

Greetings! I have added `abort()`, `abort(String)`, and `abort(Supplier<String>)` methods into the `Assumptions` class, along with the relevant tests and release notes. These are analogous to the `fail` methods in the `Assertions` class in that they do not validate anything but just abort the current test. 

I found myself looking for a method like this a while back and was surprised they did not exist already. These now allow you to write some more complex business logic around the assumption and to fail it with one neat `abort()` call, instead of an ugly `assumeTrue(false)` or `assumeFalse(true)` call.

---

I hereby agree to the terms of the [JUnit Contributor License Agreement](https://github.com/junit-team/junit5/blob/002a0052926ddee57cf90580fa49bc37e5a72427/CONTRIBUTING.md#junit-contributor-license-agreement).

---

### Definition of Done

- [x] There are no TODOs left in the code
- [x] Method [preconditions](https://junit.org/junit5/docs/snapshot/api/org.junit.platform.commons/org/junit/platform/commons/util/Preconditions.html) are checked and documented in the method's Javadoc

About this -- the pre-existing assumptions and failure methods did not do any precondition validation either, so I did not add such a thing in these `abort` methods either. It definitely will crash to a NullPointerException if someone passes a `null` `Supplier<String>` to it, but hey, the person writing the tests needs to bear some responsibility too, right?

- [x] [Coding conventions](https://github.com/junit-team/junit5/blob/HEAD/CONTRIBUTING.md#coding-conventions) (e.g. for logging) have been followed
- [x] Change is covered by [automated tests](https://github.com/junit-team/junit5/blob/HEAD/CONTRIBUTING.md#tests) including corner cases, errors, and exception handling
- [x] Public API has [Javadoc](https://github.com/junit-team/junit5/blob/HEAD/CONTRIBUTING.md#javadoc) and [`@API` annotations](https://apiguardian-team.github.io/apiguardian/docs/current/api/org/apiguardian/api/API.html)
- [x] Change is documented in the [User Guide](https://junit.org/junit5/docs/snapshot/user-guide/) and [Release Notes](https://junit.org/junit5/docs/snapshot/user-guide/#release-notes)

The User Guide I haven't edited, but the release notes ("release-notes-5.9.0-M1.adoc") I did edit. I think it would be enough for these methods to appear in the JavaDocs and the Release Notes, would you agree?

- [x] All [continuous integration builds](https://github.com/junit-team/junit5#continuous-integration-builds) pass

### CODE REVIEW

**Comment by ZeroOne3010** [comment]
I'll just mark the final checkbox, method preconditions, as done as it is in line with the current implementation.

**Comment by ZeroOne3010** [comment]
@sbrannen Hi, any idea on the future of this PR? It has been a while. I've just rebased this on `main` and resolved the conflicts again.

**Comment by marcphilipp** [comment]
@ZeroOne3010 Thanks for your contribution! 👍

**Comment by ZeroOne3010** [comment]
Thank you! 😊

**Pull request merged**
