### PR TITLE
Issues/2381 provide concise test feed details

### PR DESCRIPTION
**Pull request by halitanildonmez**
## Overview

Hello! 

I have attempted to fix issue #2381 

What I added: 

1. Details option now takes comma separated values now
2. Added a new mode called testfeed
3. Added unit tests for it
4. TestFeed prints according to https://github.com/junit-team/junit5/issues/2381#issuecomment-674025977

Questions: 

1. Are there colors you need there ? How should the coloring scheme should look like ? 
2. Should we print containers ? Like override testPlanExecutionStarted or dynamicTestRegistered ? 
3. Code needs feedback as I am not sure whether it looks as expected

---

I hereby agree to the terms of the [JUnit Contributor License Agreement](https://github.com/junit-team/junit5/blob/002a0052926ddee57cf90580fa49bc37e5a72427/CONTRIBUTING.md#junit-contributor-license-agreement).

---

### Definition of Done

- [x] There are no TODOs left in the code
- [ ] Method [preconditions](https://junit.org/junit5/docs/snapshot/api/org.junit.platform.commons/org/junit/platform/commons/util/Preconditions.html) are checked and documented in the method's Javadoc
- [x] [Coding conventions](https://github.com/junit-team/junit5/blob/HEAD/CONTRIBUTING.md#coding-conventions) (e.g. for logging) have been followed
- [x] Change is covered by [automated tests](https://github.com/junit-team/junit5/blob/HEAD/CONTRIBUTING.md#tests) including corner cases, errors, and exception handling
- [x] Public API has [Javadoc](https://github.com/junit-team/junit5/blob/HEAD/CONTRIBUTING.md#javadoc) and [`@API` annotations](https://apiguardian-team.github.io/apiguardian/docs/current/api/org/apiguardian/api/API.html)
- [ ] Change is documented in the [User Guide](https://junit.org/junit5/docs/snapshot/user-guide/) and [Release Notes](https://junit.org/junit5/docs/snapshot/user-guide/#release-notes)
- [ ] All [continuous integration builds](https://github.com/junit-team/junit5#continuous-integration-builds) pass

### CODE REVIEW

**Comment by sormuras** [comment]
Hi Halit,

First and foremost: thank you for your work on this topic. I'll answer your question inline below.

> Are there colors you need there ? How should the coloring scheme should look like ?

You're using `Color.DYNAMIC` in every case — please change it to more appropriate constants, derived from the method name and the test identifier (execution result) properties. Take a look at [FlatPrintingListener.java](https://github.com/junit-team/junit5/blob/main/junit-platform-console/src/main/java/org/junit/platform/console/tasks/FlatPrintingListener.java) for examples.
Especially: `Color color = Color.valueOf(testExecutionResult);`

> Should we print containers ? Like override testPlanExecutionStarted or dynamicTestRegistered ?

No, I don't think so. `testfeed` is about announcing tests when they are started and finished. Not their containers, nor about test plan or registration related events.

> Code needs feedback as I am not sure whether it looks as expected

You are mixing two aspects into one PR: adding the `testfeed` feature and changing the `--details` mode option. Those two aspects deserve dedicated PRs, making them easier to implement, test, and review.
- Please, remove the changes related to the `--details` mode from this PR. Let's focus on adding the `testfeed` feature here.

**Review by sormuras — CHANGES_REQUESTED** [review]
See https://github.com/junit-team/junit5/pull/2414#issuecomment-1076076676

**Comment by halitanildonmez** [comment]
Hi Christian! 

Thank you for the feedback, I will fix it asap!

**Comment by halitanildonmez** [comment]
@sormuras I think I have fixed the issues, can you take a look ? I hope I understood you correctly

**Comment by halitanildonmez** [comment]
There are some failures regarding spotlessJava check. I ran them locally and they seem fine for me.  Also 
I ran :documentation:consoleLauncherTest locally and they also pass. Do I need a newer java version maybe ? Or is it good to go ?

```
Execution failed for task ':junit-platform-console:spotlessJavaCheck'.
> The following files had format violations:
      src/main/java/org/junit/platform/console/tasks/TestFeedPrintingListener.java
          @@ -1,5 +1,5 @@
           /*
          -·*·Copyright·2015-2020·the·original·author·or·authors.
          +·*·Copyright·2015-2022·the·original·author·or·authors.
           ·*
           ·*·All·rights·reserved.·This·program·and·the·accompanying·materials·are
           ·*·made·available·under·the·terms·of·the·Eclipse·Public·License·v2.0·which
  Run './gradlew :junit-platform-console:spotlessApply' to fix these violations.
```

**Comment by sormuras** [comment]
I'll take a look the coming days.

Don't worry about the formatting, there's something off on `main` branch since https://github.com/junit-team/junit5/commit/92f8e211e05f5a762f583a6f6c7165a879fe45e7

**Comment by marcphilipp** [comment]
@halitanildonmez Thanks for your PR and sorry it took us so long to get back to it. We'll take it from here.

**Pull request closed without merging**
