### PR TITLE
Introduce IterationSelector

### LINKED ISSUE #2738: Introduce iterationSelector DiscoverySelector to JUnit Platform
## Motivation

With this [commit](https://github.com/spockframework/spock/commit/90427874f5ccde29be8cfb35c0f3450244bd8dd1) Spock got the capability to select individual iterations via their `UniqueId`. This works great for re-running a test from the IDE, but it doesn't work well if you don't have a prior run to obtain the `UniqueId` as we don't want external tools to create these IDs themselves.

Spock_Run_Iteration

## Possible Solution

`DiscoverySelectors.iterationSelector(MethodSelector method, int... iterationIndices)`

This would re-use the existing `MethodSelector` to select the method and accept a varargs of indices to select which iterations to run.

## Deliverables

- [ ] Add a `DiscoverySelectors.iterationSelector(...)`

### PR DESCRIPTION
**Pull request by marcphilipp**
Resolves #2738.

### CODE REVIEW

**Comment by marcphilipp** [comment]
I added support to select iterations via `ConsoleLauncher`:

```
$ gw :documentation:consoleLauncher --args="--select-iteration=method:example.ParameterizedTestDemo#palindromes(java.lang.String)[0,2]"
Using gradle at '/Users/marc/Repositories/junit5/gradlew' to run buildfile '/Users/marc/Repositories/junit5/build.gradle.kts':

Type-safe dependency accessors is an incubating feature.
Type-safe project accessors is an incubating feature.

> Task :documentation:consoleLauncher

Thanks for using JUnit! Support its development at https://junit.org/sponsoring

╷ 
├─ JUnit Vintage ✔
├─ JUnit Platform Suite ✔
└─ JUnit Jupiter ✔
   └─ ParameterizedTestDemo ✔
      └─ palindromes(String) ✔
         ├─ [1] candidate=racecar ✔
         └─ [3] candidate=able was I ere I saw elba ✔

Test run finished after 131 ms
[         5 containers found      ]
[         0 containers skipped    ]
[         5 containers started    ]
[         0 containers aborted    ]
[         5 containers successful ]
[         0 containers failed     ]
[         2 tests found           ]
[         0 tests skipped         ]
[         2 tests started         ]
[         0 tests aborted         ]
[         2 tests successful      ]
[         0 tests failed          ]


BUILD SUCCESSFUL in 4s
95 actionable tasks: 33 executed, 62 up-to-date

Publishing build scan...
https://ge.junit.org/s/rhvdhs6tzwz7o
```

**Comment by sormuras** [comment]
Had a another brief look at this PR and I like it.

- What should other (not Jupiter, Vintage, TestNGine) TestEngine implementors add to their engines in order to support this new selector?
- Is the CLI syntax "just" an extension of the already exsting one? For example, would those work?
  - `-select-iteration="method:example.ParameterizedTestDemo#palindromes(java.lang.String)[0,2]"`
  - `-select-method="example.ParameterizedTestDemo#palindromes(java.lang.String)"`

**Comment by marcphilipp** [comment]
> What should other (not Jupiter, Vintage, TestNGine) TestEngine implementors add to their engines in order to support this new selector?

They'd have to check for `IterationSelector` as another `DiscoverySelector` if they have a use case where that makes sense (see spockframework/spock#1379 for an example).

> Is the CLI syntax "just" an extension of the already exsting one? For example, would those work?

Yes, they would. The syntax is  `--select-iteration="<TYPE>:<VALUE>[<INDEX>(,<INDEX>)]" where `<VALUE>` is the string that would normally be passed to `--select-<TYPE>`.

**Review by sormuras — APPROVED** [review]
Looks good to me.

**Pull request merged**
