### PR TITLE
Use Docker images from GitHub Container Registry

### PR DESCRIPTION
**Pull request by marcphilipp**

### CODE REVIEW

**Comment by jbduncan** [comment]
Is there any way we can review the source code for the new container images?

**Comment by jbduncan** [comment]
Ah, the Dockerfiles are published over at https://github.com/junit-team/build-env, aren't they? :)

**Comment by marcphilipp** [comment]
Yep, that's right.

**Comment by jbduncan** [comment]
LGTM so far!

**Pull request merged**
