### PR TITLE
Introduce before and after callbacks at the Jupiter engine-level

### PR DESCRIPTION
**Pull request by sormuras**
## Overview

Addresses #456 

This PR is a basis for discussion. Error handling and documentation are left out on-purpose.

### Usage
```java
@BeforeEngineExecution
static void before0() {
	countBefore0++;
}

@BeforeEngineExecution
static void before0(ExtensionContext context) {
	context.getStore(ExtensionContext.Namespace.GLOBAL).put("alpha", "omega");
	countBefore0++;
}

@AfterEngineExecution
static void after0(ExtensionContext context) {
	assertEquals("omega", context.getStore(ExtensionContext.Namespace.GLOBAL).get("alpha"));
	countAfter0++;
}

@AfterEngineExecution
void after0NonStatic(ExtensionContext context) {
	assertEquals("omega", context.getStore(ExtensionContext.Namespace.GLOBAL).get("alpha"));
	countAfter0++;
}
```

### Implementation notes

* If a single parameter `ExtensionContext` is declared in an annotated method, the root `ExtensionContext` of `JupiterEngineExecutionContext` is injected at runtime.
* `@BeforeEngineExecution`-annotated methods must be `static`.
* `@AfterEngineExecution`-annotated methods must be `static`. If you're using `@TestInstance(TestInstance.Lifecycle.PER_CLASS)`, `@AfterEngineExecution`-annotated methods don't have be `static`.
* ~~`@ExtendWith(AlphaOmega.class)` does **not** work at the moment.~~

---

I hereby agree to the terms of the JUnit Contributor License Agreement.

---

### Definition of Done

- [ ] There are no TODOs left in the code
- [ ] Method [preconditions](http://junit.org/junit5/docs/snapshot/api/org/junit/platform/commons/util/Preconditions.html) are checked and documented in the method's Javadoc
- [ ] [Coding conventions](https://github.com/junit-team/junit5/blob/master/CONTRIBUTING.md#coding-conventions) (e.g. for logging) have been followed
- [ ] Change is covered by [automated tests](https://github.com/junit-team/junit5/blob/master/CONTRIBUTING.md#tests)
- [ ] Public API has [Javadoc](https://github.com/junit-team/junit5/blob/master/CONTRIBUTING.md#javadoc) and [`@API` annotations](http://junit.org/junit5/docs/snapshot/api/org/junit/platform/commons/meta/API.html)
- [ ] Change is documented in the [User Guide](http://junit.org/junit5/docs/snapshot/user-guide/) and [Release Notes](http://junit.org/junit5/docs/snapshot/user-guide/#release-notes)
- [ ] All [continuous integration builds](https://github.com/junit-team/junit5#continuous-integration-builds) pass

### CODE REVIEW

**Comment by sebersole** [comment]
Sorry if I missed it, but how are these picked up?  Can they exist anywhere (i.e. across multiple test classes)?

**Comment by sormuras** [comment]
As implemented in this PR, they are discovered in every class that "contains" tests.

But we might drop the entire idea and this PR in particular in favor for a broader solution like discussed in #744

**Comment by sebersole** [comment]
I should point out though that I am personally more interested in the corresponding extension corollary to these annotations - although I guess how they registered there would be questionable (service?).

**Comment by sormuras** [comment]
If you want to play with this PR in your sample projects - direct your dependency resolver to jitpack, that host a compiled and packed version of this branch: 
https://jitpack.io/com/github/junit-team/junit5/issues~456-jupiter-engine-level-callbacks-SNAPSHOT/build.log

...almost. Jitpack (and others) seems to suffer from `server certificate change is restricted during renegotiation` issues.

**Comment by sormuras** [comment]
Superseded by #1174

**Comment by luolong** [comment]
Actually, I am rather keen on the idea of before- and after callbacks on the (Jupiter) test engine level.

My use-case is that the code base we are writing tests over is sometimes heavily time-dependent. We are using JodaTime for accessing current time in production code and JodaTime has a concept of a `MillisProvider` which is a global state that all methods that return current time use under the covers to get current milliseconds value.

To be able to improve stability with time dependent tests, we need to override this `MillisProvider` so that we could control time in our tests. That on the other hand is also problematic because if every test now overrides global time, we cannot run these tests in parallel as they may well start overriding the global state.

A solution would be to initialize custom `MillisProvider` with the _`TestEngine`_ that keeps separate time per thread using `ThreadLocal` context and only manipulate time through this test double API.

As a bonus, I could clean up and reset the global `MillisProvider` to the default one when the test engine has finished running all the tests.

**Comment by luolong** [comment]
As for the discovery mechanism. 

Because this is such a deep integration with test engine that there is no good natural context where to define such classes, why not use _ServiceLoader_ for initializing test engine extensions?

**Comment by sormuras** [comment]
If I understand your use-case correctly, it can be implemented similar to the example in #1174 -- on first access, create and store your `MillisProvider` at the engine level context and use that singleton instance throughout your tests. When the context store is closed, restore the global `MillisProvider` to the default.

You won't get the exact system instant millis the engine "started" with this approach, but you may refer to the instant your resource is created and stored.

**Comment by luolong** [comment]
Yes, that could work.

**Pull request closed without merging**
