### PR TITLE
[WIP] [5.3] Remove `junit-platform-gradle-plugin` from build configuration

### PR DESCRIPTION
**Pull request by sormuras**
## Overview

This PR removes the `junit-platform-gradle-plugin` from build configuration. It does **not** delete the directory.

Addresses part of #1331

Note: Do **not** press the "Rebase and merge" button, yet. Wait until `5.3.0-SNAPSHOT` is active on `master`.

---

I hereby agree to the terms of the [JUnit Contributor License Agreement](https://github.com/junit-team/junit5/blob/master/CONTRIBUTING.md#junit-contributor-license-agreement).

### CODE REVIEW

**Comment by sbrannen** [comment]
> We haven't release 5.2, yet. So, this is too early, isn't it?

Yeah... but I think that's why @sormuras slated it for `5.3 M1`. 😉

**Comment by sbrannen** [comment]
But then again, making the changes against the current `master` is perhaps a bit risky this early in the game.

**Comment by sormuras** [comment]
Don't press the "Rebase and merge" button, yet. Wait until `5.3.0-SNAPSHOT` is active on `master`.

**Comment by sbrannen** [comment]
I think [WIP] in the title should be replace with [RIP].

https://twitter.com/sam_brannen/status/995986481310248960

🤣

**Pull request closed without merging**
