### PR TITLE
Add platform configuration parameter for test MethodOrderer

### PR DESCRIPTION
**Pull request by joschi**
## Overview

Similar to the `junit.jupiter.testinstance.lifecycle.default` configuration setting, users of the JUnit platform might want to configure the default test method order globally for all tests instad of adding the `@TestMethodOrder` annotation on every test class.

This change set adds the `junit.jupiter.testmethod.order.default` configuration setting, which sets the default test method order for the whole JUnit platform.

If `junit.jupiter.testmethod.order.default` has not been set or contains an invalid value, the default test method order is being used, otherwise the specified `MethodOrderer`.

---

I hereby agree to the terms of the [JUnit Contributor License Agreement](https://github.com/junit-team/junit5/blob/002a0052926ddee57cf90580fa49bc37e5a72427/CONTRIBUTING.md#junit-contributor-license-agreement).

---

### Definition of Done

- [x] There are no TODOs left in the code
- [x] Method [preconditions](https://junit.org/junit5/docs/snapshot/api/org/junit/platform/commons/util/Preconditions.html) are checked and documented in the method's Javadoc
- [x] [Coding conventions](https://github.com/junit-team/junit5/blob/master/CONTRIBUTING.md#coding-conventions) (e.g. for logging) have been followed
- [x] Change is covered by [automated tests](https://github.com/junit-team/junit5/blob/master/CONTRIBUTING.md#tests) including corner cases, errors, and exception handling
- [x] Public API has [Javadoc](https://github.com/junit-team/junit5/blob/master/CONTRIBUTING.md#javadoc) and [`@API` annotations](https://apiguardian-team.github.io/apiguardian/docs/current/api/org/apiguardian/api/API.html)
- [ ] Change is documented in the [User Guide](https://junit.org/junit5/docs/snapshot/user-guide/) and [Release Notes](https://junit.org/junit5/docs/snapshot/user-guide/#release-notes)
- [ ] All [continuous integration builds](https://github.com/junit-team/junit5#continuous-integration-builds) pass

### CODE REVIEW

**Comment by joschi** [comment]
I didn't update the documentation yet until somebody confirmed that this is useful.
After this, I'll update the documentation accordingly.

**Comment by sbrannen** [comment]
Tentatively slated for 5.7 M2 for _team discussion_

**Comment by sbrannen** [comment]
**Team Decision**: Introduce support for a new `junit.jupiter.testmethod.order.default` global configuration parameter that will be used to configure the default `MethodOrderer` used to order test methods if `@TestMethodOrder` is not present on the test class.

**Comment by marcphilipp** [comment]
Thanks for the PR, @joschi! 👍

**Pull request merged**
