### PR TITLE
Compile and test on Java 12

### PR DESCRIPTION
**Pull request by sormuras**
## Overview

#1951

---

I hereby agree to the terms of the [JUnit Contributor License Agreement](https://github.com/junit-team/junit5/blob/002a0052926ddee57cf90580fa49bc37e5a72427/CONTRIBUTING.md#junit-contributor-license-agreement).

---

### Definition of Done

- [x] There are no TODOs left in the code
- [x] Method [preconditions](https://junit.org/junit5/docs/snapshot/api/org/junit/platform/commons/util/Preconditions.html) are checked and documented in the method's Javadoc
- [x] [Coding conventions](https://github.com/junit-team/junit5/blob/master/CONTRIBUTING.md#coding-conventions) (e.g. for logging) have been followed
- [x] Change is covered by [automated tests](https://github.com/junit-team/junit5/blob/master/CONTRIBUTING.md#tests) including corner cases, errors, and exception handling
- [ ] Public API has [Javadoc](https://github.com/junit-team/junit5/blob/master/CONTRIBUTING.md#javadoc) and [`@API` annotations](https://apiguardian-team.github.io/apiguardian/docs/current/api/org/apiguardian/api/API.html)
- [x] Change is documented in the [User Guide](https://junit.org/junit5/docs/snapshot/user-guide/) and [Release Notes](https://junit.org/junit5/docs/snapshot/user-guide/#release-notes)
- [x] All [continuous integration builds](https://github.com/junit-team/junit5#continuous-integration-builds) pass

### CODE REVIEW

**Comment by sormuras** [comment]
@brunoborges @ethomson How do we get Java 12 running on Mac and Windows?

**Comment by sormuras** [comment]
Related issue https://github.com/MicrosoftDocs/vsts-docs/issues/2675

**Comment by ethomson** [comment]
Good question - the [macOS images](https://github.com/microsoft/azure-pipelines-image-generation/blob/master/images/macos/macos-10.14-Readme.md) should have JDK 12.  So you shouldn't need to use the java installer.

It looks like Windows does not (though you could chocolatey install them) have JDK 12 installed, though.  So you could use the java installer, but you need to point it to a java archive.  If you specify `jdkSourceOption: AzureStorage` then you need to [specify the azure storage information](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/java-tool-installer?view=azure-devops) where the JDK is to unpack and install.

You could also just [use chocolatey](https://chocolatey.org/packages/openjdk
), eg:

```
choco install openjdk --version 12.0.1
```

**Comment by sormuras** [comment]
Thanks for chiming in, Edward. Will tune the PR accordingly...

**Comment by sormuras** [comment]
_cough_ and where do I put those commands...

- Mac: `export JAVA_HOME="${JAVA_HOME_12_X64}"`
- Win: `choco install openjdk --version 12.0.1`

...into the `azure-pipelines.yml`?

**Comment by sormuras** [comment]
Hm, seems like my latest blind/educated guesses were spot on... 😎

**Comment by sormuras** [comment]
...except for the Windows job. The installed JDK 12 didn't not "persist" from its install task to the test task.

**Comment by ethomson** [comment]
> ...except for the Windows job. The installed JDK 12 didn't not "persist" from its install task to the test task.

Right - that makes sense, the `PATH` would have gotten reset between invocations.  🤔

**Comment by ethomson** [comment]
Maybe pass the path to the template?  Something like:

```
  steps:
    - bash: choco install openjdk --version 12.0.1
    - checkout: self
      fetchDepth: 10
    - template: src/azure/azure-gradle-step.yml
      parameters:
        path: "C:\Program Files\OpenJDK\jdk-12.0.1\bin"
```

and in `azure-gradle-step.yml`:

```
if [ -n "${{ parameters.path }}" ]; then
    export PATH="${{ parameters.path }}:$PATH"
fi
```

(note: totally untested)

**Comment by sormuras** [comment]
Making progress...

```
------------------------------------------------------------
Gradle 5.5.1
------------------------------------------------------------
Build time:   2019-07-10 20:38:12 UTC
Revision:     3245f748c7061472da4dc184991919810f7935a5
Kotlin:       1.3.31
Groovy:       2.5.4
Ant:          Apache Ant(TM) version 1.9.14 compiled on March 12 2019
JVM:          12.0.1 (Oracle Corporation 12.0.1+12)
OS:           Windows Server 2019 10.0 amd64
```

**Comment by sormuras** [comment]
Only the _Coverage_ job complains about: `ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.`

Almost There

**Comment by sormuras** [comment]
Javadoc layout is still ... _off_...

**Pull request merged**
