### PR TITLE
Reduce stack utilization of TestTemplateTestDescriptor::execute

### PR DESCRIPTION
**Pull request by amaembo**
## Overview

Fixes issue #4020

---

I hereby agree to the terms of the [JUnit Contributor License Agreement](https://github.com/junit-team/junit5/blob/002a0052926ddee57cf90580fa49bc37e5a72427/CONTRIBUTING.md#junit-contributor-license-agreement).

---

### Definition of Done

- [x] There are no TODOs left in the code
- [x] Method [preconditions](https://junit.org/junit5/docs/snapshot/api/org.junit.platform.commons/org/junit/platform/commons/util/Preconditions.html) are checked and documented in the method's Javadoc -- no method declarations changed
- [x] [Coding conventions](https://github.com/junit-team/junit5/blob/HEAD/CONTRIBUTING.md#coding-conventions) (e.g. for logging) have been followed
- [x] Change is covered by [automated tests](https://github.com/junit-team/junit5/blob/HEAD/CONTRIBUTING.md#tests) including corner cases, errors, and exception handling -- refactoring only change, I believe no new tests are necessary
- [x] Public API has [Javadoc](https://github.com/junit-team/junit5/blob/HEAD/CONTRIBUTING.md#javadoc) and [`@API` annotations](https://apiguardian-team.github.io/apiguardian/docs/current/api/org/apiguardian/api/API.html) -- no public APIs changed
- [x] Change is documented in the [User Guide](https://junit.org/junit5/docs/snapshot/user-guide/) and [Release Notes](https://junit.org/junit5/docs/snapshot/user-guide/#release-notes) -- should I write something there, or the change is minor and doesn't worth mentioning?

### CODE REVIEW

**Review by marcphilipp — APPROVED** [review]

**Comment by amaembo** [comment]
Not sure about formatting. I've formatted the changed fragment using spotlessApply, even though it's inside the `formatter:off` section. Probably it worth removing `formatter:off`.

**Comment by jbduncan** [comment]
> Not sure about formatting. I've formatted the changed fragment using spotlessApply, even though it's inside the `formatter:off` section. Probably it worth removing `formatter:off`.

I think so too. From what I've observed of Spotless over the years, users like JUnit 5 use `formatter:(off|on)` because the bundled Eclipse formatter can't handle fluent chains like streams very well, so the comments are used as an escape hatch. Thus they should be safe to remove, if the team is happy of course. :)

**Comment by marcphilipp** [comment]
Agreed, let's remove them

**Comment by marcphilipp** [comment]
@amaembo Thank you for your contribution! I polished it a bit in c29dbb2d7f78161bf6adfe3bc187918610ce98ac.

**Pull request merged**
