### PR TITLE
Add Android support to the Gradle plugin

### PR DESCRIPTION
**Pull request by aurae**
## Overview

See #204 for a discussion on the topic.

- Extended `JUnit5Plugin` to detect applied Android plugins and tailor task creation to its environment
- Added tests for Android environment (**Note:** This requires an Android SDK installation on the target machine)

---

I hereby agree to the terms of the JUnit Contributor License Agreement.

### CODE REVIEW

**Comment by marcphilipp** [comment]
@aurae Thanks for submitting the pull request! Have you noticed that the build on Travis failed?

**Comment by aurae** [comment]
Yes, I have! After checking the `.travis.yaml` config file used in this project, it failing on the Android-related tests is most definitely related to the VM not having access to an installation of the Android SDK. I have verified these errors on a machine without the proper setup (that is, a missing `ANDROID_HOME` environment variable, as well as the SDK located in the folder it's pointing to).

Usually, Travis configuration for Android projects is set up by specifying `language: android`, along with some additional properties. [Here's a minimal example of what that looks like](https://github.com/journeyapps/android-maven-example/blob/master/.travis.yml). I'm hesitant to change JUnit's `.travis.yaml` to that on a global level, though, just because the Gradle plugin happens to be compatible with Android. Then again, the alternative would be [to `wget` the SDK and configure everything manually](http://gmariotti.blogspot.de/2014/04/integrating-android-github-repo-with.html), which would pollute Travis' configuration as well.

I will perform some tests regarding the change to `language: android` for this project's modules - in theory, the image should be identical to the Java one, but extended with the components which are required for the new tests.

**Comment by jlink** [comment]
You could make the android tests conditional so that they are only executed if an android sdk is available. 

Von meinem iPad gesendet

**Comment by aurae** [comment]
Great hint! I have added conditional execution to the new test cases now, and made them dependent on the presence of the required environment variable.

**Comment by aurae** [comment]
I'm closing this in favor of #499, which honors the current codebase better than this older version.

**Pull request closed without merging**
