### PR TITLE
Prune suite discovery result before use

### PR DESCRIPTION
**Pull request by mpkorstanje**
## Overview

Fixes: #2838.

---

I hereby agree to the terms of the [JUnit Contributor License Agreement](https://github.com/junit-team/junit5/blob/002a0052926ddee57cf90580fa49bc37e5a72427/CONTRIBUTING.md#junit-contributor-license-agreement).

---

### Definition of Done

- [x] There are no TODOs left in the code
- [x] Method [preconditions](https://junit.org/junit5/docs/snapshot/api/org.junit.platform.commons/org/junit/platform/commons/util/Preconditions.html) are checked and documented in the method's Javadoc
- [x] [Coding conventions](https://github.com/junit-team/junit5/blob/HEAD/CONTRIBUTING.md#coding-conventions) (e.g. for logging) have been followed
- [x] Change is covered by [automated tests](https://github.com/junit-team/junit5/blob/HEAD/CONTRIBUTING.md#tests) including corner cases, errors, and exception handling
- [x] Public API has [Javadoc](https://github.com/junit-team/junit5/blob/HEAD/CONTRIBUTING.md#javadoc) and [`@API` annotations](https://apiguardian-team.github.io/apiguardian/docs/current/api/org/apiguardian/api/API.html)
- [x] Change is documented in the [User Guide](https://junit.org/junit5/docs/snapshot/user-guide/) and [Release Notes](https://junit.org/junit5/docs/snapshot/user-guide/#release-notes)
- [ ] All [continuous integration builds](https://github.com/junit-team/junit5#continuous-integration-builds) pass

### CODE REVIEW

**Review by marcphilipp — APPROVED** [review]
Thanks for the PR! I've moved the filtering to `SuiteTestDescriptor` so it's closer to where the additional filter was applied and felt more natural to only consider its remaining children.

**Comment by marcphilipp** [comment]
@mpkorstanje Could you please review my changes?

**Review by mpkorstanje — COMMENTED** [review]
Looks better!

I was stil puzling over the test plan created by the suite launcher.

Currently it doesn't have any roots. Which is fine for the limited internal use case we have right now but may come back to be a problem later.

**Comment by mpkorstanje** [comment]
@marcphilipp I've pushed 052ecea1a2f2fab94ac73235577493ffecd0fefd to preserve the `allIdentifiers.size() == children.size() + roots.size()` invariant when a test plan is used by a suite. It does assume that identifiers are added by traversing the test hierarchy from top to bottom.

**Review by marcphilipp — APPROVED** [review]

**Comment by marcphilipp** [comment]
@mpkorstanje Thanks! 👍

**Pull request merged**
