### PR TITLE
Fix NPE when deserializing `TestIdentifier`

### PR DESCRIPTION
**Pull request by dmlloyd**
## Overview

Fix `NullPointerException` when a `TestIdentifier` with no `parentId` is deserialized.

Issue: #3819

---

I hereby agree to the terms of the [JUnit Contributor License Agreement](https://github.com/junit-team/junit5/blob/002a0052926ddee57cf90580fa49bc37e5a72427/CONTRIBUTING.md#junit-contributor-license-agreement).

---

### Definition of Done

- [x] There are no TODOs left in the code
- [x] Method [preconditions](https://junit.org/junit5/docs/snapshot/api/org.junit.platform.commons/org/junit/platform/commons/util/Preconditions.html) are checked and documented in the method's Javadoc
- [x] [Coding conventions](https://github.com/junit-team/junit5/blob/HEAD/CONTRIBUTING.md#coding-conventions) (e.g. for logging) have been followed
- [x] Change is covered by [automated tests](https://github.com/junit-team/junit5/blob/HEAD/CONTRIBUTING.md#tests) including corner cases, errors, and exception handling
- [x] Public API has [Javadoc](https://github.com/junit-team/junit5/blob/HEAD/CONTRIBUTING.md#javadoc) and [`@API` annotations](https://apiguardian-team.github.io/apiguardian/docs/current/api/org/apiguardian/api/API.html)
- [x] Change is documented in the [User Guide](https://junit.org/junit5/docs/snapshot/user-guide/) and [Release Notes](https://junit.org/junit5/docs/snapshot/user-guide/#release-notes)

### CODE REVIEW

**Comment by dmlloyd** [comment]
Hmm CI is failing due to a spotless check for a file I didn't touch: https://github.com/junit-team/junit5/actions/runs/9114769155/job/25059506872?pr=3820#step:3:731

Did I mess something up somehow?

**Comment by dmlloyd** [comment]
Also one more question... is there any chance that this change could be backported into a 5.10.3 release?

**Comment by marcphilipp** [comment]
> I don't really understand how the descriptors and identifiers work together though so I just created an anonymous instance of `TestDescriptors` with the exact characteristics that trigger the problem. Is that OK?

I polished the test to make it more like the others in that class in 85a300c29ec14bd239f1c474c2258aef3f7cfd47.

> Hmm CI is failing due to a spotless check for a file I didn't touch: [junit-team/junit5/actions/runs/9114769155/job/25059506872?pr=3820#step:3:731](https://github.com/junit-team/junit5/actions/runs/9114769155/job/25059506872?pr=3820#step:3:731)
> 
> Did I mess something up somehow?

That was my bad. Earlier today, I pushed something to `main` that broke that. I just fixed it and merged the fix into your branch. Should be good now.

> Also one more question... is there any chance that this change could be backported into a 5.10.3 release?

Would a 5.11.0-M2 release also work for you?

**Review by marcphilipp — APPROVED** [review]

**Comment by dmlloyd** [comment]
> > I don't really understand how the descriptors and identifiers work together though so I just created an anonymous instance of `TestDescriptors` with the exact characteristics that trigger the problem. Is that OK?
> 
> I polished the test to make it more like the others in that class in [85a300c](https://github.com/junit-team/junit5/commit/85a300c29ec14bd239f1c474c2258aef3f7cfd47).

Great! Thanks.

> > Hmm CI is failing due to a spotless check for a file I didn't touch: [junit-team/junit5/actions/runs/9114769155/job/25059506872?pr=3820#step:3:731](https://github.com/junit-team/junit5/actions/runs/9114769155/job/25059506872?pr=3820#step:3:731)
> > Did I mess something up somehow?
> 
> That was my bad. Earlier today, I pushed something to `main` that broke that. I just fixed it and merged the fix into your branch. Should be good now.

Awesome!

> > Also one more question... is there any chance that this change could be backported into a 5.10.3 release?
> 
> Would a 5.11.0-M2 release also work for you?

I'm not sure; I'll follow up once I've consulted with the team.

**Comment by geoand** [comment]
> Would a 5.11.0-M2 release also work for you?

Is there any chance we can see a preliminary changelog for `5.11`? We have never encountered any issues upgrading in the past, but I would nevertheless like us to do our due diligence :)

**Comment by marcphilipp** [comment]
Sure, here are the release notes for [M1](https://junit.org/junit5/docs/5.11.0-M1/release-notes/) and the preliminary ones for [M2](https://github.com/junit-team/junit5/blob/main/documentation/src/docs/asciidoc/release-notes/release-notes-5.11.0-M2.adoc).

**Comment by geoand** [comment]
Thanks!

**Comment by marcphilipp** [comment]
@dmlloyd @geoand We just released 5.11.0-M2

**Comment by geoand** [comment]
🙏

**Comment by geoand** [comment]
@marcphilipp thanks again, for the release! We tried and it and this fix works expected, however because the milestone release has some other effects that we would ideally like to avoid dealing with until a GA, release, is there any chance we could get a `5.10.3`?

Thanks a lot

**Comment by dmlloyd** [comment]
And relatedly, would it be useful if I put up a backport of this PR to the 5.10.x branch?

**Comment by dmlloyd** [comment]
Just in case, I've opened #3837.

**Comment by sbrannen** [comment]
@dmlloyd and @geoand,

I've opened #3838 so the team can consider backporting selected bug fixes to `5.10.x`.

**Comment by geoand** [comment]
Thanks a lot @sbrannen!

**Pull request merged**
