### PR TITLE
Stop further suite discovery when encountering a cycle

### PR DESCRIPTION
**Pull request by mpkorstanje**
## Overview

It is relatively easy to create a test suite that contains itself by accident. E.g:

```java
package org.example.tag;

@Tag("fast")
public class FastTest {
    @Test
    public void test() {
        System.out.println("I am fast test");
    }
}
```
```java
package org.example.tag;

@Tag("slow")
public class SlowTest {
    @Test
    public void test() {
        System.out.println("I am slow test");
    }
}
```
```java
package org.example.tag;

@SelectPackages("org.example.tag")
@IncludeTags("fast")
@Suite
public class TestSuite {
}
```

This configuration will result in a a long stack trace with a message explaining that the suite contained a cycle.

```
Configuration error: The suite configuration may not contain a cycle [[engine:junit-platform-suite]/[suite:org.example.tag.TestSuite]/[engine:junit-platform-suite]/[suite:org.example.tag.TestSuite]]
```

And it is is not immediately apparent how a user should resolve this problem. This example could be resolved by explicitly excluding the suite engine by adding `@ExcludeEngine("junit-platform-suite")`. This prevents further discovery.  But when multiple suites are involved this may not be right action.

Fortunately the suite itself is aware of the cycle and as stopping further discovery is the only reasonable action. This means that this can be done without any sort of explicit configuration.

Fixes: #3115

---

I hereby agree to the terms of the [JUnit Contributor License Agreement](https://github.com/junit-team/junit5/blob/002a0052926ddee57cf90580fa49bc37e5a72427/CONTRIBUTING.md#junit-contributor-license-agreement).

---

### Definition of Done

- [x] There are no TODOs left in the code
- [x] Method [preconditions](https://junit.org/junit5/docs/snapshot/api/org.junit.platform.commons/org/junit/platform/commons/util/Preconditions.html) are checked and documented in the method's Javadoc
- [x] [Coding conventions](https://github.com/junit-team/junit5/blob/HEAD/CONTRIBUTING.md#coding-conventions) (e.g. for logging) have been followed
- [x] Change is covered by [automated tests](https://github.com/junit-team/junit5/blob/HEAD/CONTRIBUTING.md#tests) including corner cases, errors, and exception handling
- [x] Public API has [Javadoc](https://github.com/junit-team/junit5/blob/HEAD/CONTRIBUTING.md#javadoc) and [`@API` annotations](https://apiguardian-team.github.io/apiguardian/docs/current/api/org/apiguardian/api/API.html)
- [x] Change is documented in the [User Guide](https://junit.org/junit5/docs/snapshot/user-guide/) and [Release Notes](https://junit.org/junit5/docs/snapshot/user-guide/#release-notes)
- [x] All [continuous integration builds](https://github.com/junit-team/junit5#continuous-integration-builds) pass

### CODE REVIEW

**Comment by marcphilipp** [comment]
@mpkorstanje Thanks for the PR! I think we should include it for 5.9.2, though. Any objections?

**Review by marcphilipp — APPROVED** [review]

**Comment by mpkorstanje** [comment]
@marcphilipp no objections. Though the current main branch contains work for 5.10. How would this be released with 5.9.2?

**Comment by marcphilipp** [comment]
I'd essentially cherry-pick it to the `releases/5.9.x` branch.

**Comment by mpkorstanje** [comment]
Prepped for 5.9.2.

**Comment by marcphilipp** [comment]
@mpkorstanje Thank you! 👍

**Pull request merged**
