### PR TITLE
Introduce IndicativeSentences display name generator

### PR DESCRIPTION
**Pull request by olcbean**
Overview
---

Issue: #1596

---

I hereby agree to the terms of the [JUnit Contributor License Agreement](https://github.com/junit-team/junit5/blob/002a0052926ddee57cf90580fa49bc37e5a72427/CONTRIBUTING.md#junit-contributor-license-agreement).

---

### Definition of Done

- [x] There are no TODOs left in the code
- [x] Method [preconditions](http://junit.org/junit5/docs/snapshot/api/org/junit/platform/commons/util/Preconditions.html) are checked and documented in the method's Javadoc
- [x] [Coding conventions](https://github.com/junit-team/junit5/blob/master/CONTRIBUTING.md#coding-conventions) (e.g. for logging) have been followed
- [x] Change is covered by [automated tests](https://github.com/junit-team/junit5/blob/master/CONTRIBUTING.md#tests) including corner cases, errors, and exception handling
- [x] Public API has [Javadoc](https://github.com/junit-team/junit5/blob/master/CONTRIBUTING.md#javadoc) and [`@API` annotations](http://junit.org/junit5/docs/snapshot/api/org/junit/platform/commons/meta/API.html)
- [ ] Change is documented in the [User Guide](http://junit.org/junit5/docs/snapshot/user-guide/) and [Release Notes](http://junit.org/junit5/docs/snapshot/user-guide/#release-notes)
- [ ] All [continuous integration builds](https://github.com/junit-team/junit5#continuous-integration-builds) pass

### CODE REVIEW

**Comment by sormuras** [comment]
Thanks for the PR.

Can you please rebase onto `junit-team:master`, this will help to get the Travis CI build happy.

### More levels of nesting

Would it make sense to extend the generator to handle arbitrary levels of inner classes? Or is a single level enough?

Food for thought:

```java
@DisplayNameGeneration(IndicativeSentences.class)
class Some_Spec {
  @Nested
  class Begin {
    @Nested
    class Second {   
      @Nested
      class Third {
        // here be more @Nested-annotated classes
        @Test
        void end() {}
      }
    }
  }
}
```

#### Display Name for method `end()`

"Begin second third [...] end."

#### Prepend top-level name

"Some spec: Begin second third [...] end."

#### Display Name for method `end()` with "and"

"Begin and second and third [and ...] and end."

#### Display Name for method `end()` with "and"/"then"

"Begin and second and third [and ...] then end."

**Comment by olcbean** [comment]
@sormuras thank you for your feedback! I just rebased; can you kick another CI when you have the chance?

The current implementation results in `Some Spec begin second third [...] end()`. If the user wants to 'cut' `Some Spec` ( the top most level ) or any other lower level, they can simply define `@DisplayNameGeneration(IndicativeSentences.class)` at a different level or redefine it, i.e.
```
@DisplayNameGeneration(IndicativeSentences.class)
class Some_Spec {
  @DisplayNameGeneration(IndicativeSentences.class)
  @Nested
  class Begin {
    @Nested
    class Second {   
      @Nested
      class Third {
        // here be more @Nested-annotated classes
        @Test
        void end() {}
      }
    }
  }
}
```
results in `Begin second third [...] end()`. Another option to 'cut' is actually to specify explicit `@DisplayName` at a lower level, i.e.
```
@DisplayNameGeneration(IndicativeSentences.class)
class Some_Spec {
  @DisplayName("First")
  @Nested
  class Begin {
    @Nested
    class Second {   
      @Nested
      class Third {
        // here be more @Nested-annotated classes
        @Test
        void end() {}
      }
    }
  }
}
```
results in `First second third [...] end()`.

>"Some spec: Begin second third [...] end."

This is actually a little bit cumbersome to achieve with the implementation. The user will need to define something like 
```
@DisplayNameGeneration(DisplayNameGenerator.IndicativeSentences.class)
@DisplayName("Some Spec:")
@Nested class Some_Spec {
```

> **Display Name for method end() with "and"**
>"Begin and second and third [and ...] and end."
>***Display Name for method end() with "and"/"then"**
>"Begin and second and third [and ...] then end."

Interesting ideas! I am wary of implicit 'localization'. If a user is using French naming convention then it would be *strange* to have something like `<French> and <French>, then <French>`. What do you think?

This is the first implementation and the one I think is the most flexible ( for a user ) to decide where, how and when to use this feature. Maybe this is not what you had in mind? 

For this display name generator it is actually more challenging to decide what to implement than how to implement it ( isn't this usually the case ;) ) So any feedback and ideas are really appreciated!

Please let me know how to proceed. As this is my first contribution I really appreciate your guidance ;)

**Comment by sormuras** [comment]
> [...] I just rebased; can you kick another CI when you have the chance?

That happens auto-magically on commits. ;-)

Thanks for your detailed explanation. Will look into your implementation in more detail soon. From what I saw and what you describe I really like your approach. Hadn't localization in my mind last time, so forget about the hard-coded `"and"` and `"then"` connectors.

I would get rid of the terminating `()` by replacing them with a `.`

**Comment by olcbean** [comment]
Hey @sormuras! Did you have a chance to take a look at this ;)

**Comment by sormuras** [comment]
Not in detail, yet. Planning to review this and #1615 after **5.4-M1** is released.

**Comment by sbrannen** [comment]
Closing due to suggested move to JUnit Pioneer.

**Pull request closed without merging**
