### PR TITLE
Add around() to Node to allow intercepting the whole execution

### PR DESCRIPTION
**Pull request by leonard84**
## Overview

as discussed with @marcphilipp 

---

I hereby agree to the terms of the [JUnit Contributor License Agreement](https://github.com/junit-team/junit5/blob/002a0052926ddee57cf90580fa49bc37e5a72427/CONTRIBUTING.md#junit-contributor-license-agreement).

---

### Definition of Done

- [x] There are no TODOs left in the code
- [x] Method [preconditions](http://junit.org/junit5/docs/snapshot/api/org/junit/platform/commons/util/Preconditions.html) are checked and documented in the method's Javadoc
- [x] [Coding conventions](https://github.com/junit-team/junit5/blob/master/CONTRIBUTING.md#coding-conventions) (e.g. for logging) have been followed
- [x] Change is covered by [automated tests](https://github.com/junit-team/junit5/blob/master/CONTRIBUTING.md#tests) including corner cases, errors, and exception handling
- [x] Public API has [Javadoc](https://github.com/junit-team/junit5/blob/master/CONTRIBUTING.md#javadoc) and [`@API` annotations](https://apiguardian-team.github.io/apiguardian/docs/current/api/org/apiguardian/api/API.html)
- [ ] Change is documented in the [User Guide](http://junit.org/junit5/docs/snapshot/user-guide/) and [Release Notes](http://junit.org/junit5/docs/snapshot/user-guide/#release-notes)
- [x] All [continuous integration builds](https://github.com/junit-team/junit5#continuous-integration-builds) pass

### CODE REVIEW

**Comment by sbrannen** [comment]
> as discussed with @marcphilipp

Can you please provide a rationale for the proposed change (perhaps linking to an existing issue or discussion) and include that in the commit message as well?

Thanks in advance!

**Comment by sbrannen** [comment]
Tentatively slated for 5.4 M1 for _team discussion_.

**Comment by marcphilipp** [comment]
The rationale is to support Spock's extension model that allows to intercept, i.e. wrap, the whole execution of a test class, method, or invocation.

**Comment by sbrannen** [comment]
> The rationale is to support Spock's extension model that allows to intercept, i.e. wrap, the whole execution of a test class, method, or invocation.

OK. Thanks for the background.

But... doesn't this change then relate to #80 and #157?

And if so, has there been any effort made to ensure that this change would work nicely with those (once implemented)?

**Comment by marcphilipp** [comment]
I think it's related in a way because both #80 and #157 will require a similar wrapping pattern. However, in both case on a much more fine-grained level, e.g. only the `@BeforeEach` method or the `@Test` method. I don't think the Jupiter `Nodes` will override this `around()` method and therefore I don't think it will make it any easier or harder to implement #80 and #157.

**Comment by sormuras** [comment]
After last deliverables are finished:

- [ ] Change is documented in the User Guide and Release Notes

**Comment by marcphilipp** [comment]
I've added release notes and manually pushed this PR to `master` in https://github.com/junit-team/junit5/commit/77c39f2dd762d536653c180b3c1a44ab3acb19f5.

**Pull request closed without merging**
