### PR TITLE
Upgrade to Gradle 3.2

### PR DESCRIPTION
**Pull request by sormuras**
## Overview

Upgrade to Gradle 3.2

See https://discuss.gradle.org/t/gradle-3-2-released/20441
Fixes UTF-8 emission bug described in the realm of #524 -- explicitly here https://github.com/junit-team/junit5/issues/369#issuecomment-246772931

---

I hereby agree to the terms of the JUnit Contributor License Agreement.

### CODE REVIEW

**Comment by sbrannen** [comment]
This has been merged into `master`.

Thanks

**Comment by sbrannen** [comment]
Next time, please make sure you actually run `gradle wrapper` after updating the wrapper version. 😉  (see 264f52bdd5714b9dccd393d45f46fb2cc35afc1f).

**Comment by sormuras** [comment]
Pardon the inconvenience.

I just saw the two textual changes in https://github.com/junit-team/junit5/commit/224ac22aa27f65d5bebf7c284418c75605e65d15 and thought that'd be all. Missed a) the binary and b) the Gradle update instructions.

Next time.

**Comment by sbrannen** [comment]
> Pardon the inconvenience.

No worries!

And well... it could be that I forgot to "do the right thing" that time. 😉 

It happens to the best of us.

In any case, I now typically run `gradle wrapper; gradle --version` twice... _just to be sure_... before committing. Plus, when you do it that way, there is no need to update the `gradle-wrapper.properties` file manually: it will get updated automatically.

**Pull request merged**
