### PR TITLE
Jekyll-based website

### PR DESCRIPTION
**Pull request by marcphilipp**
## Overview

This adds a Jekyll-based website that only consists of a single page so far. It contains links to User Guide, Javadoc, and GitHub. In addition, it includes a "Upcoming Events" section that has been prefilled using data from #222.

Related issue: #205.

---

I hereby agree to the terms of the JUnit Contributor License Agreement.

### CODE REVIEW

**Comment by nicolaiparlog** [comment]
I like the upcoming events. :+1:

If they could get an ID, the link could be more specific, which might help if they move someplace else on the page.

**Comment by marcphilipp** [comment]
You mean the "Upcoming Events" heading should get an id?

**Comment by nicolaiparlog** [comment]
Yes, exactly. Sorry for being vague, it's early. ;)

**Comment by marcphilipp** [comment]
That's perfectly fine. I've added a TODO on #205 to add an ID to the Upcoming Events heading. Thanks for the suggestion!

**Pull request merged**
