### PR TITLE
Add space before method name.

### PR DESCRIPTION
**Pull request by hotchemi**
## Overview

- Add space before method name.

---

I hereby agree to the terms of the JUnit Contributor License Agreement.

### CODE REVIEW

**Comment by hotchemi** [comment]
Oh is this your formatter rule? Didn't know that....

**Comment by marcphilipp** [comment]
The build fails because our formatter settings are enforced by the Spotless Gradle plugin. However, I would actually like to have spaces where you've added them. If you want, you might want to look into changing the formatter settings.

**Comment by hotchemi** [comment]
Sorry I'm not sure which id is correct to fix in the junit-eclipse-formatter-settings.xml. Could u point out soon?

**Comment by sbrannen** [comment]
We are currently using Spotless 1.3.2 which uses the formatting functionality of Eclipse 4.5, and the behavior seen here is due to a [bug in Eclipse 4.5](https://bugs.eclipse.org/bugs/show_bug.cgi?id=472962#c5).

This bug has been fixed in Eclipse 4.5.1 and 4.6.

Thus, we will simply have to wait on a release of Spotless that uses Eclipse 4.5.1+.

**Comment by sbrannen** [comment]
FYI: I have raised an issue with Spotless: https://github.com/diffplug/spotless/issues/15

**Comment by marcphilipp** [comment]
Thanks, Sam!

**Comment by sbrannen** [comment]
This pull request has been superseded by #183.

I am therefore closing this PR.

**Comment by hotchemi** [comment]
OK.

**Pull request closed without merging**
