### PR TITLE
Move to java-library plugin

### PR DESCRIPTION
**Pull request by eddumelendez**
## Overview

Modify existing configuration names by `api` or `implementation`.

See gh-691

---

I hereby agree to the terms of the JUnit Contributor License Agreement.

---

### Definition of Done

- [X] There are no TODOs left in the code
- [X] Method [preconditions](http://junit.org/junit5/docs/snapshot/api/org/junit/platform/commons/util/Preconditions.html) are checked and documented in the method's Javadoc
- [X] [Coding conventions](https://github.com/junit-team/junit5/blob/master/CONTRIBUTING.md#coding-conventions) (e.g. for logging) have been followed
- [X] Change is covered by [automated tests](https://github.com/junit-team/junit5/blob/master/CONTRIBUTING.md#tests)
- [X] Public API has [Javadoc](https://github.com/junit-team/junit5/blob/master/CONTRIBUTING.md#javadoc) and [`@API` annotations](http://junit.org/junit5/docs/snapshot/api/org/junit/platform/commons/meta/API.html)
- [] Change is documented in the [User Guide](http://junit.org/junit5/docs/snapshot/user-guide/) and [Release Notes](http://junit.org/junit5/docs/snapshot/user-guide/#release-notes)
- [X] All [continuous integration builds](https://github.com/junit-team/junit5#continuous-integration-builds) pass

### CODE REVIEW

**Comment by sormuras** [comment]
Changes made by @eddumelendez are straight-forward and consistent, the PR checks are green. LGTM.

@marcphilipp what do you think?

**Comment by jbduncan** [comment]
I'm personally not so sure about making junit-commons part of the API, as is currently done... Are there any parts of it that definitely need to be exposed to end users or tool writers?

**Comment by sormuras** [comment]
> [...] not so sure about making junit-commons part of the API [...]

- https://github.com/junit-team/junit5/tree/master/junit-platform-commons/src/main/java/org/junit/platform/commons/annotation
- https://github.com/junit-team/junit5/tree/master/junit-platform-commons/src/main/java/org/junit/platform/commons/support

...are maintained API and published.

**Comment by jbduncan** [comment]
Ah, silly me! Thanks for clearing things up for me @sormuras. :)

**Comment by sormuras** [comment]
Thanks @eddumelendez

**Comment by gaganis** [comment]
Kudos @eddumelendez!

**Pull request merged**
