### PR TITLE
Update text and link to IntelliJ IDEA in the User Guide

### PR DESCRIPTION
**Pull request by askoulikari-jetbrains**
## Overview

Hi team! My name is Anna Skoulikari and I'm a technical writer working at JetBrains. The team would like to edit the link text to make it more generic and change the link it points to so that we can manage what resource we link to more effectively. 

---

I hereby agree to the terms of the [JUnit Contributor License Agreement](https://github.com/junit-team/junit5/blob/002a0052926ddee57cf90580fa49bc37e5a72427/CONTRIBUTING.md#junit-contributor-license-agreement).

---

### Definition of Done

- [X] There are no TODOs left in the code
- [X] Method [preconditions](https://junit.org/junit5/docs/snapshot/api/org.junit.platform.commons/org/junit/platform/commons/util/Preconditions.html) are checked and documented in the method's Javadoc
- [X] [Coding conventions](https://github.com/junit-team/junit5/blob/HEAD/CONTRIBUTING.md#coding-conventions) (e.g. for logging) have been followed
- [X] Change is covered by [automated tests](https://github.com/junit-team/junit5/blob/HEAD/CONTRIBUTING.md#tests) including corner cases, errors, and exception handling
- [X] Public API has [Javadoc](https://github.com/junit-team/junit5/blob/HEAD/CONTRIBUTING.md#javadoc) and [`@API` annotations](https://apiguardian-team.github.io/apiguardian/docs/current/api/org/apiguardian/api/API.html)
- [X] Change is documented in the [User Guide](https://junit.org/junit5/docs/snapshot/user-guide/) and [Release Notes](https://junit.org/junit5/docs/snapshot/user-guide/#release-notes)

### CODE REVIEW

**Comment by sbrannen** [comment]
This has been merged into `main` in 67b8f8bef242894788fb2ce4517f4720ecdee361 and revised in e160aec2655857e05c2732254e9fe468e0425403.

Thanks

**Comment by askoulikari-jetbrains** [comment]
@sbrannen thank you so much for letting me know this was merged into main. Just so I can make sure the change is public. Do you have any idea when the change will be [updated on the website](https://junit.org/junit5/docs/current/user-guide/#running-tests-ide-intellij-idea)? 
Screenshot 2024-04-11 at 10 52 57

**Comment by sormuras** [comment]
The [snapshot](https://junit.org/junit5/docs/snapshot/user-guide/#running-tests-ide-intellij-idea) version of the website is already up.

The `current` version will be updated when either 5.11 or 5.10.x is released. We don't have a date fixed for them. We'll update https://github.com/junit-team/junit5/milestones accordingly.

**Comment by askoulikari-jetbrains** [comment]
@sormuras thank you so much for letting me know, sounds good! (-:

**Comment by marcphilipp** [comment]
I've create the `releases/5.10.2-docs` branch based on the `r5.10.2` tag, cherr-picked the two commits and republished the website to expedite the changes going live.

@askoulikari-jetbrains The docs now contain the updated text and link.

**Comment by askoulikari-jetbrains** [comment]
@marcphilipp Hi Marc! Thank you so much for getting back to me. I had a quick question about the text that the team edited, we had specific reasons for the chosen wording ("... for more information consult the following IntelliJ IDEA resource.")

We purposefully wanted to keep the wording a bit more broad because we are not necessarily planning on linking it to the official IntelliJ IDEA documentation. (Even at the moment, it does not link to the official documentation.)

Would it be possible to use the original wording our team chose, or is this perhaps something the team would want to discuss with us?

**Comment by sbrannen** [comment]
Hi @askoulikari-jetbrains,

Thanks for letting us know that you would prefer wording that does not explicitly mention "the official documentation.

Regarding the original proposal, I chose not to use that since there is nothing "following" the statement, and we do our best to ensure that statements made in the User Guide are logical.

However, I'll update the sentence as follows, which hopefully meets your needs.

> For more information, please consult this [IntelliJ IDEA resource](https://jb.gg/junit-idea/).

**Comment by sbrannen** [comment]
@askoulikari-jetbrains, I revised the wording in 804af548080eede28238745b0bbdc89d13678087.

@marcphilipp, can you publish that change like you did last time?

Thanks!

**Comment by marcphilipp** [comment]
Done

**Comment by askoulikari-jetbrains** [comment]
@sbrannen @marcphilipp Yes, great you latest edit is good! Thank you! (-:

**Pull request closed without merging**
