### PR TITLE
Upgrade to AssertJ 3.15.0

### PR DESCRIPTION
**Pull request by epeee**
## Overview

see https://assertj.github.io/doc/#assertj-core-3-15-0-release-notes for details.

I hereby agree to the terms of the [JUnit Contributor License Agreement](https://github.com/junit-team/junit5/blob/002a0052926ddee57cf90580fa49bc37e5a72427/CONTRIBUTING.md#junit-contributor-license-agreement).

---

### Definition of Done

- [ ] There are no TODOs left in the code
- [ ] Method [preconditions](https://junit.org/junit5/docs/snapshot/api/org/junit/platform/commons/util/Preconditions.html) are checked and documented in the method's Javadoc
- [ ] [Coding conventions](https://github.com/junit-team/junit5/blob/master/CONTRIBUTING.md#coding-conventions) (e.g. for logging) have been followed
- [ ] Change is covered by [automated tests](https://github.com/junit-team/junit5/blob/master/CONTRIBUTING.md#tests) including corner cases, errors, and exception handling
- [ ] Public API has [Javadoc](https://github.com/junit-team/junit5/blob/master/CONTRIBUTING.md#javadoc) and [`@API` annotations](https://apiguardian-team.github.io/apiguardian/docs/current/api/org/apiguardian/api/API.html)
- [ ] Change is documented in the [User Guide](https://junit.org/junit5/docs/snapshot/user-guide/) and [Release Notes](https://junit.org/junit5/docs/snapshot/user-guide/#release-notes)
- [ ] All [continuous integration builds](https://github.com/junit-team/junit5#continuous-integration-builds) pass

### CODE REVIEW

**Comment by sormuras** [comment]
The underlying reason for why the build fails can be seen in this stacktrace:

```
  JUnit Jupiter:EngineTestKitAllEventsDemo:verifyAllJupiterEvents()
    MethodSource [className = 'example.testkit.EngineTestKitAllEventsDemo', methodName = 'verifyAllJupiterEvents', methodParameterTypes = '']
    =&gt; java.lang.IllegalArgumentException: Could not create type
       org.assertj.core@3.15.0/org.assertj.core.internal.bytebuddy.TypeCache.findOrInsert(TypeCache.java:154)
       org.assertj.core@3.15.0/org.assertj.core.internal.bytebuddy.TypeCache$WithInlineExpunction.findOrInsert(TypeCache.java:365)
       org.assertj.core@3.15.0/org.assertj.core.api.SoftProxies.createSoftAssertionProxyClass(SoftProxies.java:124)
       org.assertj.core@3.15.0/org.assertj.core.api.SoftProxies.createSoftAssertionProxy(SoftProxies.java:110)
       org.assertj.core@3.15.0/org.assertj.core.api.AbstractSoftAssertions.proxy(AbstractSoftAssertions.java:32)
       [...]
     Caused by: java.lang.NoClassDefFoundError: java/lang/instrument/Instrumentation
       org.assertj.core@3.15.0/org.assertj.core.internal.bytebuddy.utility.JavaModule$Dispatcher$CreationAction.run(JavaModule.java:352)
       org.assertj.core@3.15.0/org.assertj.core.internal.bytebuddy.utility.JavaModule$Dispatcher$CreationAction.run(JavaModule.java:331)
       java.base/java.security.AccessController.doPrivileged(AccessController.java:310)
       org.assertj.core@3.15.0/org.assertj.core.internal.bytebuddy.utility.JavaModule.&lt;clinit&gt;(JavaModule.java:44)
       org.assertj.core@3.15.0/org.assertj.core.internal.bytebuddy.dynamic.loading.ClassInjector$UsingReflection$Dispatcher$CreationAction.run(ClassInjector.java:452)
       [...]
     Caused by: java.lang.ClassNotFoundException: java.lang.instrument.Instrumentation
       java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
       java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
       java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
       [...]
```

/cc @raphw ... seems like module `java.instrument` is required by ByteBuddy by default?

Related issue: https://github.com/joel-costigliola/assertj-core/issues/1504

**Comment by raphw** [comment]
It does "require static" and normally, unless you are loading Java agent related classes, it should not be a problem; but it seems like I missed a spot. I will need to go through the code base, I guess. I don't have any tests on it, unfortunately.

**Comment by sormuras** [comment]
Thanks for looking into it.

**Comment by raphw** [comment]
Alright, the mistake was a reference to `Instrumentation.class` rather then using `Class.forName("java.lang.instrument.Instrumentation")` for the case it's not loaded as a module.

Could you do me the favor of cloning and building Byte Buddy from master and rerun your steps to see if that fix was sufficient?

**Comment by sormuras** [comment]
You mean build AssertJ with Byte Buddy shaded from master?

**Comment by raphw** [comment]
Indeed, I can do this myself.

**Comment by raphw** [comment]
Seems to work with the current master branch. Can you confirm that?

**Comment by sormuras** [comment]
Will give it a shot tonight.

Rafael Winterhalter <notifications@github.com> schrieb am Mi., 5. Feb.
2020, 13:32:

**Comment by sormuras** [comment]
...i guess the best way to ensure future compat. is an end-to-end test in AssertJ itself. Like using a modular test setup using its latest master build including Byte Buddy -- which should fail at the moment.

I'll prepare a PR ...  @joel-costigliola ;-)

**Comment by sormuras** [comment]
5 out of 14068 tests in AssertJ Core are failing on master (on Windows):

image

Will skip tests for the time being...

**Comment by sormuras** [comment]
Trying to get a `master-SNAPSHOT` version of Byte Buddy via JitPack: https://jitpack.io/com/github/raphw/byte-buddy/master-SNAPSHOT/build.log

**Comment by sormuras** [comment]
Only failed due to `Could not find artifact com.github.raphw.byte-buddy:byte-buddy-android-test:${android.sort}:master-byte-buddy-1.10.7-gd9a5b3a-5 in jitpack.io (https://jitpack.io)` ... because that library couldn't be build via JitPack.

Underlying reason:
```
Review license that has not been accepted (y/N)? 
1/1: License android-sdk-arm-dbt-license:
...
```
So. I guess, with the latest-and-greatest Byte Buddy version shaded into AssertJ, it should work.

**Comment by raphw** [comment]
Alright, then I'll do a release. No idea why this worked some time when I believed to have tested it. I should probably run a reduced build where I exclude tests that rely on the `Instrumentation` API using a modular JVM. That would require a major clean up of my unit tests, though.

**Comment by sormuras** [comment]
Will AssertJ 3.16.0 contain the ByteBuddy version with the _java.instrument_ fix, @joel-costigliola?

**Comment by joel-costigliola** [comment]
I believe so as we are using the 1.10.8 version https://github.com/raphw/byte-buddy/releases/tag/byte-buddy-1.10.8

**Comment by sormuras** [comment]
Superseded by https://github.com/junit-team/junit5/commit/a9e8a617889510f06016bb6d805c36bcfda8550e which upgraded AssertJ to `3.16.0`.

**Pull request closed without merging**
