### PR TITLE
Issue843 gradle formatter

### PR DESCRIPTION
**Pull request by fvgh**
## Overview

Provided Gradel formatting using spotless groovy formatter, as proposed for #843.
Change is split in 3 parts:

1. Modification to gradle build
2. Manual adaptations required due to groovy formatter constraints
3. Applied groovy formatter on the gradle files

---

I hereby agree to the terms of the JUnit Contributor License Agreement.

---

### Definition of Done

- [X] There are no TODOs left in the code
- [ ] Method [preconditions](http://junit.org/junit5/docs/snapshot/api/org/junit/platform/commons/util/Preconditions.html) are checked and documented in the method's Javadoc
- [ ] [Coding conventions](https://github.com/junit-team/junit5/blob/master/CONTRIBUTING.md#coding-conventions) (e.g. for logging) have been followed
- [ ] Change is covered by [automated tests](https://github.com/junit-team/junit5/blob/master/CONTRIBUTING.md#tests)
- [ ] Public API has [Javadoc](https://github.com/junit-team/junit5/blob/master/CONTRIBUTING.md#javadoc) and [`@API` annotations](http://junit.org/junit5/docs/snapshot/api/org/junit/platform/commons/meta/API.html)
- [ ] Change is documented in the [User Guide](http://junit.org/junit5/docs/snapshot/user-guide/) and [Release Notes](http://junit.org/junit5/docs/snapshot/user-guide/#release-notes)
- [x] All [continuous integration builds](https://github.com/junit-team/junit5#continuous-integration-builds) pass

## Remaining problems
I am afraid that there is a test failure also occurring for the master branch, hence not all tests passed.

> AssertionFailedError: `Automatic-Module-Name` not found in manifest of JAR: ../junit-jupiter-migration-support/

Anyhow, maybe you can already let me know whether you consider the modifications useful.

### CODE REVIEW

**Comment by marcphilipp** [comment]
To be honest, I don't like how the Gradle build scripts look after going through the formatter.

For example, 

```
configurations {
    clover		
}```

should stay that way.

However, I'm not sure it's worth the effort to try to fine-tune Spotless with custom rules for these.

@fvgh What do you think?

**Comment by fvgh** [comment]
I am afraid the GrEclipse can not be configured in that respect and I see no way to provide reliable indentation without access to the AST.
So there is nothing I can do in that respect. It was just a proposal :smile: .

We'll have another release of Spotless soon, which simplifies the repository definition for extensions loaded on demand. With that change I can remove the [additional buildscript for allprojects](https://github.com/junit-team/junit5/pull/860/files#diff-c197962302397baf3a4cc36463dce5ea). I can provide you with a corresponding PR if you like. After that I would consider my contribution to #843 complete.

**Comment by marcphilipp** [comment]
Sounds good, thanks!

**Comment by sbrannen** [comment]
Just wanted to say that I agree with @marcphilipp here:

> To be honest, I don't like how the Gradle build scripts look after going through the formatter.

But thanks anyway for your efforts!

**Pull request closed without merging**
