### PR TITLE
Link to Truth docs instead of GitHub landing page.

### PR DESCRIPTION
**Pull request by cpovirk**
---

I hereby agree to the terms of the JUnit Contributor License Agreement.

### CODE REVIEW

**Comment by sormuras** [comment]
```
java PresentModule.java com.google.truth:truth:1.0
path = truth-1.0.jar
name = truth
mode = automatic
automatic name source = FILENAME
api = 1 package(s)
```

Not providing an AUTOMATIC-MODULE-NAME, like `com.google.truth` via its manifest...

**Comment by marcphilipp** [comment]
@sormuras Sounds like you should create an issue in Truth's issue tracker. 😉

**Comment by sormuras** [comment]
Truth.

Erm... true.

**Comment by sormuras** [comment]
Done via https://github.com/google/truth/issues/605

**Pull request merged**
