### PR TITLE
Remove the workaround for Kotlin on JDK9

### PR DESCRIPTION
**Pull request by JLLeitschuh**
As the bug was fixed in Kotlin 1.1.4 acording to youtrack this
workarround can be removed.
https://youtrack.jetbrains.com/issue/KT-18832

## Overview

Please describe your changes here and list any open questions you might have.

---

I hereby agree to the terms of the JUnit Contributor License Agreement.

---

### Definition of Done

- [x] There are no TODOs left in the code
- [x] Method [preconditions](http://junit.org/junit5/docs/snapshot/api/org/junit/platform/commons/util/Preconditions.html) are checked and documented in the method's Javadoc
- [x] [Coding conventions](https://github.com/junit-team/junit5/blob/master/CONTRIBUTING.md#coding-conventions) (e.g. for logging) have been followed
- [x] Change is covered by [automated tests](https://github.com/junit-team/junit5/blob/master/CONTRIBUTING.md#tests)
- [x] Public API has [Javadoc](https://github.com/junit-team/junit5/blob/master/CONTRIBUTING.md#javadoc) and [`@API` annotations](http://junit.org/junit5/docs/snapshot/api/org/junit/platform/commons/meta/API.html)
- [x] Change is documented in the [User Guide](http://junit.org/junit5/docs/snapshot/user-guide/) and [Release Notes](http://junit.org/junit5/docs/snapshot/user-guide/#release-notes)
- [x] All [continuous integration builds](https://github.com/junit-team/junit5#continuous-integration-builds) pass

### CODE REVIEW

**Comment by JLLeitschuh** [comment]
Very strange that now this fails on JDK 8. That's 100% not what I was expecting.

**Comment by jbduncan** [comment]
@JLLeitschuh It looks to me that Travis coincidentally timed-out when Gradle attempted and failed to download `https://plugins.gradle.org/m2/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar` after it presumably taking too long to do so.

So I think this may fix itself if you run `git commit --amend --no-fix && git push --force-with-lease`, which by my understanding would essentially re-push your latest commit and thus trick Travis CI into restarting.

**Comment by sormuras** [comment]
LGTM - awaiting feedback from the team to merge this PR as-is today.

**Comment by sbrannen** [comment]
Well, "All checks have passed".

So it looks like a _green light_ from my side. 👍

**Comment by sormuras** [comment]
Merged. Thanks, Jonathan!

**Pull request merged**
