### PR TITLE
Added DisplayName MethodOrderer

### PR DESCRIPTION
**Pull request by dylan-asos**
## Overview

Added new implementation of MethodOrderer named DisplayName, allowing you to control test execution order based on the test display name that is generated for a test method.

Added implementation, tests, user docs and release notes.

---

I hereby agree to the terms of the [JUnit Contributor License Agreement](https://github.com/junit-team/junit5/blob/002a0052926ddee57cf90580fa49bc37e5a72427/CONTRIBUTING.md#junit-contributor-license-agreement).

---

### Definition of Done

- [x] There are no TODOs left in the code
- [x] Method [preconditions](https://junit.org/junit5/docs/snapshot/api/org/junit/platform/commons/util/Preconditions.html) are checked and documented in the method's Javadoc
- [x] [Coding conventions](https://github.com/junit-team/junit5/blob/master/CONTRIBUTING.md#coding-conventions) (e.g. for logging) have been followed
- [x] Change is covered by [automated tests](https://github.com/junit-team/junit5/blob/master/CONTRIBUTING.md#tests) including corner cases, errors, and exception handling
- [ ] Public API has [Javadoc](https://github.com/junit-team/junit5/blob/master/CONTRIBUTING.md#javadoc) and [`@API` annotations](https://apiguardian-team.github.io/apiguardian/docs/current/api/org/apiguardian/api/API.html)
- [x] Change is documented in the [User Guide](https://junit.org/junit5/docs/snapshot/user-guide/) and [Release Notes](https://junit.org/junit5/docs/snapshot/user-guide/#release-notes)
- [x] All [continuous integration builds](https://github.com/junit-team/junit5#continuous-integration-builds) pass

### CODE REVIEW

**Comment by dylan-asos** [comment]
Apologies - all clear, will make changes as described

**Comment by sbrannen** [comment]
> Apologies - all clear, will make changes as described

No problem. Thanks for making the changes. It looks much better now! 👍

**Comment by sbrannen** [comment]
local merge _in progress_

**Comment by sbrannen** [comment]
This has been merged into `master`in 6fee44dc95b1cf49d85166d93a861ce0a9483d68 and further refined in 76ad6d1638bc27b45200da42b759275d938e7e9f and bbf277c82436f4d40b000ec6e4eba81da38d35fc.

Thanks

**Pull request closed without merging**
