### PR TITLE
Make module `org.junit.platform.jfr` work on Java 8

### PR DESCRIPTION
**Pull request by marcphilipp**

### CODE REVIEW

**Comment by marcphilipp** [comment]
@kriegfrj @bjhargrave Could you please take a look if there's a way to fix the [OSGi verification failure](https://ge.junit.org/s/yruijgy3rn26o/failure#1) without disabling it? It looks like the check fails because there's no `jdk.jfr` package in Java 8 but there is in OpenJDK 8u262 and later.

**Comment by bjhargrave** [comment]
> It looks like the check fails because there's no `jdk.jfr` package in Java 8

Yes, the Java 8 Platform does not define a `jdk.jfr` package, so Bnd does not know that it is available on any Java 8 runtime. You can tell Bnd that it is there by adding it to `-runsystempackages` which is already done for `jdk.internal.misc` and `sun.misc`. The following change to this branch builds successfully for me.

```diff
diff --git a/buildSrc/src/main/kotlin/osgi-conventions.gradle.kts b/buildSrc/src/main/kotlin/osgi-conventions.gradle.kts
index 00570e0337..19c147eb84 100644
--- a/buildSrc/src/main/kotlin/osgi-conventions.gradle.kts
+++ b/buildSrc/src/main/kotlin/osgi-conventions.gradle.kts
@@ -79,7 +79,7 @@ val osgiProperties by tasks.registering(WriteProperties::class) {
                property("-runee", "JavaSE-${javaLibrary.mainJavaVersion}")
        }
        property("-runrequires", "osgi.identity;filter:='(osgi.identity=${project.name})'")
-       property("-runsystempackages", "jdk.internal.misc,sun.misc")
+       property("-runsystempackages", "jdk.internal.misc,sun.misc,jdk.jfr")
 }
 
 val osgiVerification by configurations.creating {
diff --git a/junit-platform-jfr/junit-platform-jfr.gradle.kts b/junit-platform-jfr/junit-platform-jfr.gradle.kts
index 68531d9fda..9d4b613ad3 100644
--- a/junit-platform-jfr/junit-platform-jfr.gradle.kts
+++ b/junit-platform-jfr/junit-platform-jfr.gradle.kts
@@ -24,7 +24,4 @@ tasks {
        compileModule {
                options.release.set(11)
        }
-       verifyOSGi {
-               enabled = false // TODO Fix OSGi capabilities, requirements, configuration, ... wiring.
-       }
 }
```

**Comment by marcphilipp** [comment]
@bjhargrave Awesome, thanks so much! 👍

**Comment by sormuras** [comment]
Integrated the proposed changes manually via 7e80935 -- thanks for your help, @bjhargrave.

Methinks, this PR is ready to be merged. Double-checked that only the `module-info.class` targets Java 11 and all other classes target Java 8. For example:

```
javap -verbose jar:file:junit-platform-jfr-1.8.0-SNAPSHOT.jar!/org/junit/platform/jfr/UniqueId.class

Classfile jar:file:junit-platform-jfr-1.8.0-SNAPSHOT.jar!/org/junit/platform/jfr/UniqueId.class
  Last modified 08.06.2021; size 500 bytes
  SHA-256 checksum c55bdd578fe47c899caa08518683cf9062716f1e37a0b2dc11581fa3b3f6e460
  Compiled from "UniqueId.java"
interface org.junit.platform.jfr.UniqueId extends java.lang.annotation.Annotation
  minor version: 0
  major version: 52
[...]
```

**Pull request merged**
