### PR TITLE
List all tests found by Console Launcher

### PR DESCRIPTION
**Pull request by stoyanK7**
## Overview

Addresses  #2854
Lists all `TestIdentifier`s  from a `TestPlan`, result of a test discovery. Essentially same output as if one is executing the tests, but without the execution.
### Option
`--list-tests`
#### Command
`java -jar junit-platform-console-standalone-1.9.0-SNAPSHOT.jar --list-tests -cp test/ --scan-classpath`
#### Tree
command + `--details tree` yields
```
╷
├─ JUnit Vintage    
├─ CarTest    
│  ├─ testModel()    
│  └─ testMake()    
└─ JUnit Jupiter 
```
#### Verbose
command + `--details verbose` yields
```
─ JUnit Vintage
     tags: []
 uniqueId: [engine:junit-vintage]
   parent: []
├─ CarTest
     tags: []
 uniqueId: [engine:junit-jupiter]/[class:CarTest]
   parent: [engine:junit-jupiter]
   source: ClassSource [className = 'CarTest', filePosition = null]
├─ testModel()
     tags: []
 uniqueId: [engine:junit-jupiter]/[class:CarTest]/[method:testModel()]
   parent: [engine:junit-jupiter]/[class:CarTest]
   source: MethodSource [className = 'CarTest', methodName = 'testModel', methodParameterTypes = '']
├─ testMake()
     tags: []
 uniqueId: [engine:junit-jupiter]/[class:CarTest]/[method:testMake()]
   parent: [engine:junit-jupiter]/[class:CarTest]
   source: MethodSource [className = 'CarTest', methodName = 'testMake', methodParameterTypes = '']
├─ JUnit Jupiter
     tags: []
 uniqueId: [engine:junit-jupiter]
   parent: []
```
#### Flat
command + `--details flat` yields
```
JUnit Vintage ([engine:junit-vintage])
CarTest ([engine:junit-jupiter]/[class:CarTest])
testModel() ([engine:junit-jupiter]/[class:CarTest]/[method:testModel()])
testMake() ([engine:junit-jupiter]/[class:CarTest]/[method:testMake()])
JUnit Jupiter ([engine:junit-jupiter])
```
---

I hereby agree to the terms of the [JUnit Contributor License Agreement](https://github.com/junit-team/junit5/blob/002a0052926ddee57cf90580fa49bc37e5a72427/CONTRIBUTING.md#junit-contributor-license-agreement).

---

### Definition of Done

- [ ] There are no TODOs left in the code
- [ ] Method [preconditions](https://junit.org/junit5/docs/snapshot/api/org.junit.platform.commons/org/junit/platform/commons/util/Preconditions.html) are checked and documented in the method's Javadoc
- [ ] [Coding conventions](https://github.com/junit-team/junit5/blob/HEAD/CONTRIBUTING.md#coding-conventions) (e.g. for logging) have been followed
- [ ] Change is covered by [automated tests](https://github.com/junit-team/junit5/blob/HEAD/CONTRIBUTING.md#tests) including corner cases, errors, and exception handling
- [ ] Public API has [Javadoc](https://github.com/junit-team/junit5/blob/HEAD/CONTRIBUTING.md#javadoc) and [`@API` annotations](https://apiguardian-team.github.io/apiguardian/docs/current/api/org/apiguardian/api/API.html)
- [ ] Change is documented in the [User Guide](https://junit.org/junit5/docs/snapshot/user-guide/) and [Release Notes](https://junit.org/junit5/docs/snapshot/user-guide/#release-notes)
- [ ] All [continuous integration builds](https://github.com/junit-team/junit5#continuous-integration-builds) pass

### CODE REVIEW

**Comment by stoyanK7** [comment]
Yeah, I agree that `--dry-run` would be appropriate here as well. It was also suggested in the issue.

**Comment by sormuras** [comment]
Please run `[./]gradlew spotlessApply` before you push changes, that'll fix indentation related issues.

**Comment by stoyanK7** [comment]
I actually did. Don't know how that one file got away with it. Should I fix & commit?

**Comment by sormuras** [comment]
@stoyanK7 can you please resolve the conflicts introduced merging other PR onto the main branch? Thanks in advance.

**Comment by stoyanK7** [comment]
@sormuras I would like to complete this pull request. I am mostly looking at your [List all available engines](https://github.com/junit-team/junit5/commit/b9b746b4eb2b01a0123df93c85ad263d15d1fd96) pull request and believe all I have left is to make some tests and documentation. However, I can't wrap my head around how to test this - do I need some sample project to test it on and add it in the `resources` folder or how would that work?

**Pull request closed without merging**
