### PR TITLE
Remove unused constant EXCEPTION_MESSAGE_NO_ENGINE and fix typo

### PR DESCRIPTION
**Pull request by AxelMonroyX**
## Overview

- Remove unused constant `static final String EXCEPTION_MESSAGE_NO_ENGINE `
- Fix typo change 'pararameters' to 'parameters'

##### Checklist
- [x] Run `gradle clean test`
- [x] All tests are passing

---

I hereby agree to the terms of the JUnit Contributor License Agreement.

### CODE REVIEW

**Comment by AxelMonroyX** [comment]
@kcooney Hi, any idea why this 
`ERROR: JAVA_HOME is set to an invalid directory: /usr/lib/jvm/java-8-oracle-amd64`
is happening on [travis-ci](https://travis-ci.org/junit-team/junit5/jobs/178641334) ?

**Comment by marcphilipp** [comment]
@AxelMonroyX I've fixed the Travis build in master. Please rebase!

**Comment by AxelMonroyX** [comment]
@marcphilipp Thank you :+1:

**Comment by sbrannen** [comment]
This has been merged into `master`.

Thanks

**Pull request merged**
