### PR TITLE
Refactor commons module

### PR DESCRIPTION
**Pull request by hotchemi**
## Overview

- Make AnnotationCacheKey's constructor package local.
- Modify to use method reference.
- Modify to use normal String in the toString of ToStringBuilder.

---

I hereby agree to the terms of the JUnit Contributor License Agreement.

### CODE REVIEW

**Comment by jlink** [comment]
Both the StringBuilder and the method call improve readability IMO. It's on a level of detail where we allow differences in style and respect the original developer's design choice.

**Comment by stefanbirkner** [comment]
I think for a project like JUnit it is beneficial to have a consistent code style. JUnit's code will be very often read by people who are not JUnit developers. We should make their lives easy.

I think that @hotchemi's change improve readability (but readability depends on the style of the code you're used to read.)

**Comment by jlink** [comment]
I agree that a consistent style is a plus. We therefore already have a style guide and will accept PRs that make code follow it. 

The question is: To what level of depth do we want to go: Always using method refs regardless of the context? Sometimes one is better readable than the other and sometimes not. Sometimes there are compelling reasons for one style over the other and sometimes there are not. 

I'd like to give implementors more leeway to still have a style of their own. Consistency also comes with a price. Focusing too much on detail - especially in a phase like now where quite a lot of fundamentals are unclear - is a real distraction.

**Comment by hotchemi** [comment]
Sorry for the late.
When it comes to the consistency, in my opinion you should not accept various coding style.
I have no confidence how reader feel about that there is some method reference and not, but think about programmer, it helps us to remove their burden that thinking about which is good for "readability".
It's the golang philosophy(a.k.a go fmt). But of course there is another thinking like Perl or Ruby way.
It depends for junit team guys but mixing is always the cause of confusion right?

**Comment by hotchemi** [comment]
And actually Intellij always show these point...

**Comment by jlink** [comment]
There is no general hard line between _style_ and _implementation_, so let's get concrete:
- Should we have "always use method refs where possible" in our style guide?
- Should we have "always use string concatenation instead of string builder" in our style guide?
- Should we have "always use streams instead of iteration" in our style guide?
My personal opinion is "none of these". 

What do the other junit5 team members (@marcphilipp @sbrannen @mmerdes @bechte) think? We need some decision to resolve this PR and future ones along the same line...

**Comment by marcphilipp** [comment]
I agree in all three points with @jlink.

**Comment by hotchemi** [comment]
OK, should I close this PR?

**Comment by jlink** [comment]
Yes. For me it was an important pull request because it helped to get my thoughts about style and cleaning up clearer. Thanks!

**Pull request closed without merging**
