### PR TITLE
 Shallow clone during Azure Pipelines CI

### PR DESCRIPTION
**Pull request by ethomson**
## Overview

Enable shallow clone during Azure Pipelines CI.

(Unfortunately, this is configurable for each individual build run, so it needs to be repeated.)

---

I hereby agree to the terms of the [JUnit Contributor License Agreement](https://github.com/junit-team/junit5/blob/002a0052926ddee57cf90580fa49bc37e5a72427/CONTRIBUTING.md#junit-contributor-license-agreement).

---

### Definition of Done

- [ ] There are no TODOs left in the code
- [ ] Method [preconditions](http://junit.org/junit5/docs/snapshot/api/org/junit/platform/commons/util/Preconditions.html) are checked and documented in the method's Javadoc
- [ ] [Coding conventions](https://github.com/junit-team/junit5/blob/master/CONTRIBUTING.md#coding-conventions) (e.g. for logging) have been followed
- [ ] Change is covered by [automated tests](https://github.com/junit-team/junit5/blob/master/CONTRIBUTING.md#tests) including corner cases, errors, and exception handling
- [ ] Public API has [Javadoc](https://github.com/junit-team/junit5/blob/master/CONTRIBUTING.md#javadoc) and [`@API` annotations](https://apiguardian-team.github.io/apiguardian/docs/current/api/org/apiguardian/api/API.html)
- [ ] Change is documented in the [User Guide](http://junit.org/junit5/docs/snapshot/user-guide/) and [Release Notes](http://junit.org/junit5/docs/snapshot/user-guide/#release-notes)
- [ ] All [continuous integration builds](https://github.com/junit-team/junit5#continuous-integration-builds) pass

### CODE REVIEW

**Comment by ethomson** [comment]
Hmm, @marcphilipp - it looks like I broke the build?  😦

**Comment by ethomson** [comment]
> Hmm, @marcphilipp - it looks like I broke the build? 😦

Doh, no.  https://www.githubstatus.com/

**Comment by marcphilipp** [comment]
It went through once so you're not to blame. Thanks for the PR, BTW! 👍

**Comment by ethomson** [comment]
> It went through once so you're not to blame. Thanks for the PR, BTW! 👍

You bet.  I'm seeing normal authentication succeeding between the Azure Pipelines and the affected GitHub repositories, so I think the master build should be back to normal.  🤞

**Pull request merged**
