### PR TITLE
Improve exception message when a unique ID cannot be resolved to a class

### PR DESCRIPTION
**Pull request by kcooney**

### CODE REVIEW

**Comment by sbrannen** [comment]
Hi @kcooney,

Thanks for the PR.

Unfortunately, it's failing due to Spotless errors at the moment.

Can you please run `gradlew spotlessApply`, squash your commits, and force push the changes.

Thanks!

**Comment by kcooney** [comment]
@sbrannen done. I thought this would have been caught by "gradle test". Is there a better thing to run right before I submit a pull?

**Comment by jlink** [comment]
@kcooney I usually run `gradle spotlessApply build`

**Comment by marcphilipp** [comment]
`gradle check` (the equivalent of `mvn verify`) would have caught it.

**Comment by marcphilipp** [comment]
Thanks, @kcooney!

**Pull request merged**
