### PR TITLE
Activate GitHub Actions Cache

### PR DESCRIPTION
**Pull request by sormuras**
Issue #1826

## Overview

---

I hereby agree to the terms of the [JUnit Contributor License Agreement](https://github.com/junit-team/junit5/blob/002a0052926ddee57cf90580fa49bc37e5a72427/CONTRIBUTING.md#junit-contributor-license-agreement).

---

### Definition of Done

- [ ] There are no TODOs left in the code
- [ ] Method [preconditions](https://junit.org/junit5/docs/snapshot/api/org/junit/platform/commons/util/Preconditions.html) are checked and documented in the method's Javadoc
- [ ] [Coding conventions](https://github.com/junit-team/junit5/blob/master/CONTRIBUTING.md#coding-conventions) (e.g. for logging) have been followed
- [ ] Change is covered by [automated tests](https://github.com/junit-team/junit5/blob/master/CONTRIBUTING.md#tests) including corner cases, errors, and exception handling
- [ ] Public API has [Javadoc](https://github.com/junit-team/junit5/blob/master/CONTRIBUTING.md#javadoc) and [`@API` annotations](https://apiguardian-team.github.io/apiguardian/docs/current/api/org/apiguardian/api/API.html)
- [ ] Change is documented in the [User Guide](https://junit.org/junit5/docs/snapshot/user-guide/) and [Release Notes](https://junit.org/junit5/docs/snapshot/user-guide/#release-notes)
- [ ] All [continuous integration builds](https://github.com/junit-team/junit5#continuous-integration-builds) pass

### CODE REVIEW

**Comment by aepfli** [comment]
just saw this pull request and i thought i leave a questions here, i am just curious

 is there a reason why you rely on gradlew by yourself, i can understand independence might be a useful/needed goal, but there is also https://github.com/marketplace/actions/gradle-command which provide some functionality

**Comment by sormuras** [comment]
> [...] which provide some functionality

Which kind of functionality?

@marcphilipp -- with the installation of https://ge.junit.org this PR (caching on GH Actions) is superseded, isn't it?

**Comment by marcphilipp** [comment]
> with the installation of [ge.junit.org](https://ge.junit.org) this PR (caching on GH Actions) is superseded, isn't it?

Not quite. We use the remote build cache included Gradle Enterprise which contains task outputs, but we might still benefit from caching dependencies.

**Comment by sormuras** [comment]
Superseded by #2350

**Pull request closed without merging**
