### PR TITLE
Cache downloaded external dependencies and Gradle Wrapper

### PR DESCRIPTION
**Pull request by bmuschko**
## Overview

As [suggested by Travis](https://docs.travis-ci.com/user/languages/java/#Caching), cache downloaded, external dependencies and Gradle Wrapper. Subsequent builds will reuse existing files which should significantly speed up CI execution.

---

I hereby agree to the terms of the JUnit Contributor License Agreement.

---

### Definition of Done

- [x] There are no TODOs left in the code
- [x] All [continuous integration builds](https://github.com/junit-team/junit5#continuous-integration-builds) pass

### CODE REVIEW

**Comment by sormuras** [comment]
See discussion and reasoning in #1037 -- let's see, if caching really speeds things up.

**Comment by jbduncan** [comment]
I'm not sure if this PR is having or would have any impact on Travis's running time, but generally I have noticed a gradual increase in running times from one commit to the next, outside of any changes to the Travis config...

**Comment by sormuras** [comment]
@bmuschko please trigger a second build on this branch to see the cache kicking in. At least one time.

@jbduncan ... the gradual increase is real. More stuff to build, more stuff to test. Locally, I'm using `--parallel` for a `clean build` run. It saves me roughly a minute running time.

**Comment by sormuras** [comment]
### Master run
- `Ran for 7 min 25 sec`
- _no build cache active_

### Initial run of this PR
- `Ran for 8 min 18 sec`
- n.a. on initial run `Setting up build cache`
- 31.10s `changes detected, packing new archive` .... `uploading archive`

### Restarted this PR w/o code change
- `Ran for ??? sec`
- ??? on initial run `Setting up build cache`
- ??? `changes detected, packing new archive` .... `uploading archive`

**Comment by sormuras** [comment]
Initial numbers show a significant decrease in overall build duration. Which is good!

As we don't rely on any 3rd-party SNAPSHOT versions (do we?) anymore, we don't need the `--refresh-dependencies` option [introduced last year](https://github.com/junit-team/junit5/commit/baf9f7cdb5d7a70ffb41e2f3df778fe7f8ad1048#diff-354f30a63fb0907d4ad57269548329e3)?

**Comment by bmuschko** [comment]
> Initial numbers show a significant decrease in overall build duration. Which is good!

Seems like you already triggered a second build. I made another change to the code.

> As we don't rely on any 3rd-party SNAPSHOT versions (do we?) anymore, we don't need the --refresh-dependencies option introduced last year?

No, you won't need that. It's a big hammer and I believe it will check _all_ dependencies on the remote repository and not just the SNAPSHOT versions. If you just want to get the latest SNAPSHOT versions then you should configure the [TTL settings](https://docs.gradle.org/current/userguide/dependency_management.html#sec:controlling_caching). I doesn't look like you still use `--refresh-dependencies` in the `.travis.yml` file.

**Comment by sormuras** [comment]
### Code change triggered build

- `Ran for 4 min 35 sec`
- 15 sec for `Setting up build cache`
- 23 sec `changes detected, packing new archive` .... `uploading archive`

Looks even better. :) Travis CI improved here. Will merge the cache activation.

**Comment by sormuras** [comment]
> [...] doesn't look like you still use `--refresh-dependencies` in the `.travis.yml` file.

No. After turning the cache off, all dependencies were _fresh_ by definition.

> In your build code you have a check on a SNAPSHOT version for specific dependencies but you are actually not using a SNAPSHOT version. Is this check even needed?

Not sure about those. Perhaps we need them when we work on those projects again... @junit-team/junit-lambda  ?

**Comment by sormuras** [comment]
Thanks for bringing is up, Ben. Let's see if we run into build issues ... hoping the best. ;)

**Comment by bmuschko** [comment]
Sure thing!

**Comment by sormuras** [comment]
First run after activating the cache took **7 min 27 sec** - maybe because of fetching new Kotlin version. https://travis-ci.org/junit-team/junit5/jobs/317779086 

Let's continue monitoring the build times.

**Pull request merged**
