### PR TITLE
Gradle build revamp

### PR DESCRIPTION
**Pull request by aalmiray**
Streamline gradle build configuration.

Changes performed at Zurich Hackergarten 2016-05-12 with @sbrannen & @vyazelenko

---

I hereby agree to the terms of the JUnit Contributor License Agreement.

### CODE REVIEW

**Comment by marcphilipp** [comment]
Looks good to me, thanks! 👍

**Comment by marcphilipp** [comment]
This fixes #241, right?

**Comment by sbrannen** [comment]
Yep, this addresses #241. We (well, 99% Andres) just ended up doing everything in one big PR and forgot to mention the open issue number.

**Comment by sbrannen** [comment]
Merged into `master` in ea636bfb8d47f5fec872836b6415bbaa6b3b9f73.

Cheers, @aalmiray!

**Pull request closed without merging**
