### PR TITLE
Add Translations section to Overview chapter

### PR DESCRIPTION
**Pull request by sjyuan-cc**
A link to JUnit 5 User Guide(Simplified Chinese) is attached.

## Overview

Please describe your changes here and list any open questions you might have.

---

I hereby agree to the terms of the JUnit Contributor License Agreement.

---

### Definition of Done

- [ ] There are no TODOs left in the code
- [ ] Method [preconditions](http://junit.org/junit5/docs/snapshot/api/org/junit/platform/commons/util/Preconditions.html) are checked and documented in the method's Javadoc
- [ ] [Coding conventions](https://github.com/junit-team/junit5/blob/master/CONTRIBUTING.md#coding-conventions) (e.g. for logging) have been followed
- [ ] Change is covered by [automated tests](https://github.com/junit-team/junit5/blob/master/CONTRIBUTING.md#tests)
- [ ] Public API has [Javadoc](https://github.com/junit-team/junit5/blob/master/CONTRIBUTING.md#javadoc) and [`@API` annotations](http://junit.org/junit5/docs/snapshot/api/org/junit/platform/commons/meta/API.html)
- [ ] Change is documented in the [User Guide](http://junit.org/junit5/docs/snapshot/user-guide/) and [Release Notes](http://junit.org/junit5/docs/snapshot/user-guide/#release-notes)
- [ ] All [continuous integration builds](https://github.com/junit-team/junit5#continuous-integration-builds) pass

### CODE REVIEW

**Comment by smoyer64** [comment]
Wouldn't it be more effective to manage translations along side the source documents in Github?  I'm not quite sure how they'd be versioned though as the translations will tend to be a bit behind the originals.

**Comment by sormuras** [comment]
@smoyer64 _"We’ve discussed [...] in the team and we believe that including [...] translations in our repository would not work because we could never keep it up-to-date. Thus, we’d like to encourage you to host it on your own, e.g. on GitHub Pages. We’d then be happy to add a link to your translation to the top of the User Guide."_

**Comment by smoyer64** [comment]
As usual, you're way ahead of me!

**Comment by sjyuan-cc** [comment]
Hi grate junit team,
We have finished the Chinese translation and review stuff. We keep the translation updated according to the original user guide and the lasted JUnit version. For any other suggestion, Could you please give some suggestion if it would be added to the original user guide as a link.

**Comment by marcphilipp** [comment]
Merged and polished in b443f4af96e201c2370b7312a1ff36b4ff8f003d.

**Comment by hnlxl** [comment]
@sjyuan-cc http://sjyuan.cc/junit5/user-guide-cn/ now is `404 - There isn't a GitHub Pages site here.`

**Comment by marcphilipp** [comment]
@hnlxl Thanks for letting us know! I've opened #1890 to track this.

**Pull request closed without merging**
