### PR TITLE
create temp directory using system property (if available) java.io.tmpdir, use case is building some projects and be sure tmp directories are created under a configurable directory

### PR DESCRIPTION
**Pull request by olamy**
Signed-off-by: Olivier Lamy <olamy@apache.org>

## Overview

---

I hereby agree to the terms of the [JUnit Contributor License Agreement](https://github.com/junit-team/junit5/blob/002a0052926ddee57cf90580fa49bc37e5a72427/CONTRIBUTING.md#junit-contributor-license-agreement).

---

### Definition of Done

- [x] There are no TODOs left in the code
- [x] Method [preconditions](https://junit.org/junit5/docs/snapshot/api/org.junit.platform.commons/org/junit/platform/commons/util/Preconditions.html) are checked and documented in the method's Javadoc
- [x] [Coding conventions](https://github.com/junit-team/junit5/blob/HEAD/CONTRIBUTING.md#coding-conventions) (e.g. for logging) have been followed
- [ ] Change is covered by [automated tests](https://github.com/junit-team/junit5/blob/HEAD/CONTRIBUTING.md#tests) including corner cases, errors, and exception handling
- [ ] Public API has [Javadoc](https://github.com/junit-team/junit5/blob/HEAD/CONTRIBUTING.md#javadoc) and [`@API` annotations](https://apiguardian-team.github.io/apiguardian/docs/current/api/org/apiguardian/api/API.html)
- [ ] Change is documented in the [User Guide](https://junit.org/junit5/docs/snapshot/user-guide/) and [Release Notes](https://junit.org/junit5/docs/snapshot/user-guide/#release-notes)
- [ ] All [continuous integration builds](https://github.com/junit-team/junit5#continuous-integration-builds) pass

### CODE REVIEW

**Comment by sormuras** [comment]
[Java 8](https://docs.oracle.com/javase/8/docs/api/java/nio/file/Files.html#createTempDirectory-java.lang.String-java.nio.file.attribute.FileAttribute...-)
> Creates a new directory in the default temporary-file directory, using the given prefix to generate its name. The resulting Path is associated with the default FileSystem.
> This method works in exactly the manner specified by [createTempDirectory(Path,String,FileAttribute[])](https://docs.oracle.com/javase/8/docs/api/java/nio/file/Files.html#createTempDirectory-java.nio.file.Path-java.lang.String-java.nio.file.attribute.FileAttribute...-) method for the case that the dir parameter is the temporary-file directory.

Same for [Java 19](https://docs.oracle.com/en/java/javase/19/docs/api/java.base/java/nio/file/Files.html#createTempDirectory(java.lang.String,java.nio.file.attribute.FileAttribute...))

Question is: where is "default temporary-file directory" defined?

**Comment by olamy** [comment]
not locally on osx or ubuntu
```
uname -a
Darwin baguette-with-raclette.modem 22.3.0 Darwin Kernel Version 22.3.0: Mon Jan 30 20:42:11 PST 2023; root:xnu-8792.81.3~2/RELEASE_X86_64 x86_64 i386 Darwin
```
try this on osx 
```
        System.out.println("java.io.tmpdir:" + System.getProperty("java.io.tmpdir"));
        System.out.println("Files.createTempDirectory(\"foo\").toString(): " +
                Files.createTempDirectory("foo").toString());
        System.out.println("Path from @TempDir: " +  path.toString());
        System.out.println("Files.createTempDirectory(Paths.get(System.getProperty(\"java.io.tmpdir\")), \"foo\").toString()" +
                Files.createTempDirectory(Paths.get(System.getProperty("java.io.tmpdir")), "foo").toString());

```
display
```
java.io.tmpdir:/Volumes/workspace/dev/sources/open-sources/jetty/jetty.project/jetty-core/jetty-io/target
Files.createTempDirectory("foo").toString(): /var/folders/qv/jt27tybd635b14jthx54k9xw0000gn/T/foo13554605796906270922
Path from @TempDir: /var/folders/qv/jt27tybd635b14jthx54k9xw0000gn/T/junit9836155032111750782
Files.createTempDirectory(Paths.get(System.getProperty("java.io.tmpdir")), "foo").toString()/Volumes/workspace/dev/sources/open-sources/jetty/jetty.project/jetty-core/jetty-io/target/foo4087618274290999507
```

try
```
git clone https://github.com/jetty-project/jetty.project.git
cd jetty.project
mvn install -pl :jetty-io -am -Dtest=IOTest#foo
```
on ubuntu 
```
uname -a 
Linux brahman 5.15.0-60-lowlatency #66-Ubuntu SMP PREEMPT Tue Jan 24 14:26:16 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

output
```
foo test
java.io.tmpdir:/home/ubuntu/projects/jetty.project/jetty-core/jetty-io/target
Files.createTempDirectory("foo").toString(): /tmp/foo17347783670136704421
Path from @TempDir: /tmp/junit12404309779451003956
Files.createTempDirectory(Paths.get(System.getProperty("java.io.tmpdir")), "foo").toString()/home/ubuntu/projects/jetty.project/jetty-core/jetty-io/target/foo2901980636046158821
```
```

**Comment by olamy** [comment]
@sormuras correct I have been trough those jdk sources and couldn’t find something really `stable` 🤣

**Comment by olamy** [comment]
at least with this change we can have something predictable or at least what we ask with `System.setProperty("java.io.tmpdir", "target");` 
is it a jdk bug? well maybe but as said @sormuras depends what means `the default temporary-file directory`.
Yup I believed it was `java.io.tmpdir` but nope

**Comment by sormuras** [comment]
`System.setProperty(...)` at runtime might not have an effect for JDK types after initialization.

**Comment by sormuras** [comment]
FWIW, I'd favor https://github.com/junit-team/junit5/pull/2958 over this proposal.

**Comment by olamy** [comment]
> `System.setProperty(...)` at runtime might not have an effect for JDK types after initialization.

in my case it's done via maven surefire.

**Comment by olamy** [comment]
> FWIW, I'd favor #2958 over this proposal.

I don't really mind :) I only need to get something working .

**Comment by marcphilipp** [comment]
As @sormuras mentioned, the `java.io.tmpdir` system property is considered immutable after the JDK was started. Could you instead pass it as a JVM argument?

**Comment by olamy** [comment]
definitely a maven surefire issue....
when forking a jvm system properties are read from a file then configured after jvm start

**Pull request closed without merging**
