### PR TITLE
Official Gradle Wrapper Validation GitHub Action

### PR DESCRIPTION
**Pull request by JLLeitschuh**
See: https://github.com/gradle/wrapper-validation-action

### CODE REVIEW

**Comment by sormuras** [comment]
Not tested on Windows?

https://github.com/junit-team/junit5/pull/2152/checks?check_run_id=391846704#step:2:416

**Comment by JLLeitschuh** [comment]
It shouldn't need to run on windows. This is a new GitHub action. We wrote it for Linux.
No idea why that failed. Seems like the windows action is trying to evaluate our commit messages for some insane reason.

**Comment by sormuras** [comment]
> [...] Seems like the windows action is trying to evaluate our commit messages for some insane reason.

True. Very strange. 🤔

**Comment by bjhargrave** [comment]
The commit adds one file named `See: https:/github.com/gradle/wrapper-validation-action` which I don't think is the intended file name...

https://github.com/junit-team/junit5/blob/6b25883a1f7daeb2b5ef6dad3e375cfb2fb5ba46/See:%20https:/github.com/gradle/wrapper-validation-action

**Comment by JLLeitschuh** [comment]
Bahahah. Wow

**Comment by JLLeitschuh** [comment]
I'll close this an open a new one.

**Comment by JLLeitschuh** [comment]
New PR: https://github.com/junit-team/junit5/pull/2153

**Comment by sormuras** [comment]
> This is why the checkout on WIndows failed. That is not a valid file path on Windows:
> ##[error]error: invalid path 'See: https:/github.com/gradle/wrapper-validation-action'

Ha! Good Windows. Well done. 🤓

Does this mean, we under attack of a [homoglyph variant](https://github.com/gradle/wrapper-validation-action#solution) of some sort?! 😉 

> New PR: #2153

👍

**Comment by JLLeitschuh** [comment]
> Does this mean, we under attack of a homoglyph variant of some sort?! 

No, I'm clearly just clumsy with my copy-paste and things ended up in the wrong fields when using the GitHub UI to create the PR.

**Pull request closed without merging**
