### PR TITLE
Move implementation of Assertions into separate classes

### PR DESCRIPTION
**Pull request by signed**
## Overview

- Split up the implementation of Assertions into multiple classes as proposed in the [comment](https://github.com/junit-team/junit5/issues/509#issuecomment-254938200) to #509

---

I hereby agree to the terms of the JUnit Contributor License Agreement.

### CODE REVIEW

**Comment by marcphilipp** [comment]
Thanks! I think we should make the individual classes and the now public methods in there package-private. 

@junit-team/junit-lambda Do you agree?

**Comment by signed** [comment]
> since the fail(...) methods are more or less utilities and not actually assertions in their own right.

Following this reasoning shouldn't the two fail methods in `Assertions.fail(...)` be moved elsewhere e.g. `Fail.fail(...)`?

**Comment by sbrannen** [comment]
> Should I mark the classes with @API(Internal) as well?

No. Non-public types do not need to be annotated with `@API`.

**Comment by sbrannen** [comment]
> Following this reasoning shouldn't the two fail methods in `Assertions.fail(...)` be moved elsewhere e.g. `Fail.fail(...)`?

No, I don't think so.

We don't want to introduce a new class just for that purpose since that would only complicate things for users who actually need one of those two `fail(...)` methods. In other words, in terms of the public API, I think it's fine to retain those two methods in `Assertions`.

**Comment by marcphilipp** [comment]
Despite my approval, Checkstyle found an unused import. :-/

**Comment by signed** [comment]
3rd commit should fix it.
JavaDoc needed the import, but nobody else in the class. Used an absolute import in the java doc. Lets see if this fixes the problem.
While running the branch locally with ./gradlew clean spotlessApply build there where no checkstyle complaints :/

**Comment by marcphilipp** [comment]
I also cannot reproduce this locally. Actually, our Checkstyle configuration set `processJavadoc` to `true` for the `UnusedImports` module which is supposed to collect references in Javadoc. Since we're using the same Checkstyle version on AppVeyor, Travis, as well as on your machine and mine, I don't have an explanation, though.

**Comment by marcphilipp** [comment]
Thanks, @signed! 👍

**Pull request merged**
