### PR TITLE
Add "event" to event list

### LINKED ISSUE #611: Allow distinction of talk title and event name in events.json
In [`events.json`](https://github.com/junit-team/junit5/blob/gh-pages/data/events.json) individual events are specified as follows:

```json
  {
    "title": "Deep Dive into JUnit 5 - Voxxed Days Zurich 2017",
    "date": "2017-02-23",
    "location": "Zurich, Switzerland",
    "link": "https://cfp-vdz.exteso.com/2017/talk/QSX-6316/Deep_Dive_into_JUnit_5",
    "speakers": [
      "sbrannen"
    ]
}
```

Unfortunately, `title` includes the name of the talk as well as of the event - or both. It would be better to have another field for that, preferably `event`:

```json
  {
    "title": "Deep Dive into JUnit 5",
    "event": "Voxxed Days Zurich 2017",
    "date": "2017-02-23",
    "location": "Zurich, Switzerland",
    "link": "https://cfp-vdz.exteso.com/2017/talk/QSX-6316/Deep_Dive_into_JUnit_5",
    "speakers": [
      "sbrannen"
    ]
}
```

Jekyll can then create better and more flexible output.

### PR DESCRIPTION
**Pull request by nicolaiparlog**
Fixes #611 

---

I hereby agree to the terms of the JUnit Contributor License Agreement.

### CODE REVIEW

**Comment by sbrannen** [comment]
thanks!

**Comment by marcphilipp** [comment]
👍

**Comment by nicolaiparlog** [comment]
No problem. By the way, I had to sort `events.json` - how could you live like that?!  :cold_sweat: (OCD, anyone?)

**Comment by marcphilipp** [comment]
It troubled me a bit, too. 😉

**Pull request merged**
