### PR TITLE
Enhance Javadoc of InvocationInterceptor wrt. class loading

### PR DESCRIPTION
**Pull request by jonashoef**
## Overview

Added note wrt. class loading (static initialization) of the test class in `InvocationInterceptor.interceptTestClassConstructor()`'s javadoc. Depending on the structure of the test class, class loading may or may not have taken place when the method is invoked. 

---

I hereby agree to the terms of the [JUnit Contributor License Agreement](https://github.com/junit-team/junit5/blob/002a0052926ddee57cf90580fa49bc37e5a72427/CONTRIBUTING.md#junit-contributor-license-agreement).

---

### Definition of Done

- [x] There are no TODOs left in the code
- [x] Method [preconditions](https://junit.org/junit5/docs/snapshot/api/org/junit/platform/commons/util/Preconditions.html) are checked and documented in the method's Javadoc
- [x] [Coding conventions](https://github.com/junit-team/junit5/blob/master/CONTRIBUTING.md#coding-conventions) (e.g. for logging) have been followed
- [ ] Change is covered by [automated tests](https://github.com/junit-team/junit5/blob/master/CONTRIBUTING.md#tests) including corner cases, errors, and exception handling
- [ ] Public API has [Javadoc](https://github.com/junit-team/junit5/blob/master/CONTRIBUTING.md#javadoc) and [`@API` annotations](https://apiguardian-team.github.io/apiguardian/docs/current/api/org/apiguardian/api/API.html)
- [ ] Change is documented in the [User Guide](https://junit.org/junit5/docs/snapshot/user-guide/) and [Release Notes](https://junit.org/junit5/docs/snapshot/user-guide/#release-notes)
- [x] All [continuous integration builds](https://github.com/junit-team/junit5#continuous-integration-builds) pass

### CODE REVIEW

**Comment by jonashoef** [comment]
The following patch demonstrates that class loading of the test class before invocation of the InvocationInterceptor.interceptTestClassConstructor() method depends on the structure of the test class.
[InvocationInterceptor-demo-test.patch.txt](https://github.com/junit-team/junit5/files/3859955/InvocationInterceptor-demo-test.patch.txt)

**Comment by marcphilipp** [comment]
@jonashoef Thanks for the PR! I don't think that's surprising considering the [JLS](https://docs.oracle.com/javase/specs/jls/se13/html/jls-12.html#jls-12.4.1). Do you have a use case where this is problematic?

**Comment by jonashoef** [comment]
@marcphilipp Our usecase is detecting the transition between static initialization and test class constructor (for details please refer to [Issue #839](https://github.com/junit-team/junit5/issues/839)). So I was surprised that InvocationInterceptor.interceptTestClassConstructor() is invoked before a static field in the test class was assigned. I fully admit that the JLS describes the details, and there is definitely nothing wrong with InvocationInterceptor, I just thought the added note in the javadoc may help others too.

**Comment by marcphilipp** [comment]
Thanks, @jonashoef! 👍

**Pull request merged**
