### PR TITLE
Restore executable/readable directory permissions when deleting temp dir

### PR DESCRIPTION
**Pull request by Philzen**
## Overview

* Written some tests to illustrate problem #2609 (→ tests were used to fill [test matrix](https://github.com/junit-team/junit5/issues/2609#issuecomment-846634527))
* Trying to reset readable & executable permissions of `TempDir` itself and any contained files (currently failing)

---

I hereby agree to the terms of the [JUnit Contributor License Agreement](https://github.com/junit-team/junit5/blob/002a0052926ddee57cf90580fa49bc37e5a72427/CONTRIBUTING.md#junit-contributor-license-agreement).

---

### Definition of Done

- [x] There are no TODOs left in the code
- [x] Method [preconditions](https://junit.org/junit5/docs/snapshot/api/org.junit.platform.commons/org/junit/platform/commons/util/Preconditions.html) are checked and documented in the method's Javadoc
- [x] [Coding conventions](https://github.com/junit-team/junit5/blob/HEAD/CONTRIBUTING.md#coding-conventions) (e.g. for logging) have been followed
- [x] Change is covered by [automated tests](https://github.com/junit-team/junit5/blob/HEAD/CONTRIBUTING.md#tests) including corner cases, errors, and exception handling
- [x] Public API has [Javadoc](https://github.com/junit-team/junit5/blob/HEAD/CONTRIBUTING.md#javadoc) and [`@API` annotations](https://apiguardian-team.github.io/apiguardian/docs/current/api/org/apiguardian/api/API.html)
- [x] Change is documented in the [User Guide](https://junit.org/junit5/docs/snapshot/user-guide/) and [Release Notes](https://junit.org/junit5/docs/snapshot/user-guide/#release-notes)
- [x] All [continuous integration builds](https://github.com/junit-team/junit5#continuous-integration-builds) pass

### CODE REVIEW

**Comment by marcphilipp** [comment]
@Philzen Thanks for your review! I pushed another commit.

**Comment by marcphilipp** [comment]
@Philzen Please take another look and feel free to squash my commits in whichever way you like. There was some trial and error involved here due to tests only failing on Windows.

**Comment by Philzen** [comment]
@marcphilipp Thanks heaps, the tests now all pass on my machine and your refactorings make everything much more concise!

As squashing my commit into yours turned out to be really faulty (as that turns the commit causality chain on its head) i had to squash yours into mine – i hope that's OK that according to the history i'm now taking the fame for that change, which is not what i intended but it was the most workable approach :innocent: 

I took the liberty of optimizing the imports as a final commit on top.

Otherwise – i'm really happy so from my perspective this PR is good to go. Thanks again!

**Comment by Philzen** [comment]
@marcphilipp i realize you will need to approve your commits again.

Also – is there a windows based CI run so we can be sure not to introduce a regression for #2046?

**Comment by marcphilipp** [comment]
> Also – is there a windows based CI run so we can be sure not to introduce a regression for #2046?

Yes, there are CI builds on Linux, macOS, and Windows.

**Comment by marcphilipp** [comment]
@Philzen We don't use wildcard imports. Hence, the build [fails](https://scans.gradle.com/s/34bspbglcridu/console-log?task=:junit-jupiter-engine:checkstyleMain). Could you please remove those again and run `./gradlew spotlessApply` to autoformat the code (otherwise the build will fail).

**Comment by marcphilipp** [comment]
@Philzen Do you have time to finish this PR? Please let me know if you need a hand.

**Comment by Philzen** [comment]
> @Philzen We don't use wildcard imports. Hence, the build [fails](https://scans.gradle.com/s/34bspbglcridu/console-log?task=:junit-jupiter-engine:checkstyleMain). Could you please remove those again and run `./gradlew spotlessApply` to autoformat the code (otherwise the build will fail).

Sorry for the delay... so i see there's already a build chain tool that optimizes imports, guess i meant well but only made i worse by applying my intelliJ optimizations :)

My last commit has now been effectively "ironed out"  with the execution of `./gradlew spotlessApply`... so everything should be fine again :smile:

**Review by marcphilipp — APPROVED** [review]

**Comment by marcphilipp** [comment]
Thanks for your contribution, @Philzen! 👍

**Pull request merged**
