### PR TITLE
Add PULL_REQUEST_TEMPLATE.md.

### LINKED ISSUE #164: Add PULL_REQUEST_TEMPLATE
With accept conditions clause.

### PR DESCRIPTION
**Pull request by hotchemi**
## Overview

-  Fix #164.
- Add PULL_REQUEST_TEMPLATE.md.

---

I hereby agree to the terms of the JUnit Contributor License Agreement.

### CODE REVIEW

**Comment by jlink** [comment]
Have a look at the travis build failure. Even md files are checked using spotless :-/

**Comment by hotchemi** [comment]
Nice:D

**Comment by hotchemi** [comment]
Umm? Actually `gradlew spotlessApply` succeeded on my local pc...

```sh
~/w/o/junit5 ❯❯❯ ./gradlew spotlessApply                         hotchemi/164 ✱
:spotlessDocumentationApply
:spotlessGroovyApply
:spotlessJavaApply
:spotlessMiscApply
:spotlessApply
:documentation:spotlessGroovyApply
:documentation:spotlessJavaApply
:documentation:spotlessApply
:junit-commons:spotlessGroovyApply
:junit-commons:spotlessJavaApply
:junit-commons:spotlessApply
:junit-console:spotlessGroovyApply
:junit-console:spotlessJavaApply
:junit-console:spotlessApply
:junit-engine-api:spotlessGroovyApply
:junit-engine-api:spotlessJavaApply
:junit-engine-api:spotlessApply
:junit-gradle:spotlessGroovyApply
:junit-gradle:spotlessJavaApply
:junit-gradle:spotlessApply
:junit-launcher:spotlessGroovyApply
:junit-launcher:spotlessJavaApply
:junit-launcher:spotlessApply
:junit-tests:spotlessGroovyApply
:junit-tests:spotlessJavaApply
:junit-tests:spotlessApply
:junit4-engine:spotlessGroovyApply
:junit4-engine:spotlessJavaApply
:junit4-engine:spotlessApply
:junit4-runner:spotlessGroovyApply
:junit4-runner:spotlessJavaApply
:junit4-runner:spotlessApply
:junit5-api:spotlessGroovyApply
:junit5-api:spotlessJavaApply
:junit5-api:spotlessApply
:junit5-engine:spotlessGroovyApply
:junit5-engine:spotlessJavaApply
:junit5-engine:spotlessApply
:surefire-junit5:spotlessGroovyApply
:surefire-junit5:spotlessJavaApply
:surefire-junit5:spotlessApply

BUILD SUCCESSFUL

Total time: 8.772 secs

This build could be faster, please consider using the Gradle Daemon: https://docs.gradle.org/2.10/userguide/gradle_daemon.html
```

**Comment by jlink** [comment]
Here as well. Hm. Maybe a line ending issue?

**Comment by jlink** [comment]
One more idea: Add an empty line to the end of file.

**Comment by hotchemi** [comment]
I did it but still failed...and on my local even `gradlew check` succeeded :cry:

**Comment by hotchemi** [comment]
Can't figure out the reason why results of travis and local are different :cry:

**Comment by jlink** [comment]
I will merge it anyway and see if I can fix it on my machine.

**Comment by hotchemi** [comment]
Sorry, thx.

**Pull request merged**
