### PR TITLE
Remove parentheses when generating display name with ReplaceUnderscores

### PR DESCRIPTION
**Pull request by juliette-derancourt**
## Overview

Implements the improvement suggested in #1875.

---

I hereby agree to the terms of the [JUnit Contributor License Agreement](https://github.com/junit-team/junit5/blob/002a0052926ddee57cf90580fa49bc37e5a72427/CONTRIBUTING.md#junit-contributor-license-agreement).

---

### Definition of Done

- [x] There are no TODOs left in the code
- [x] Method [preconditions](http://junit.org/junit5/docs/snapshot/api/org/junit/platform/commons/util/Preconditions.html) are checked and documented in the method's Javadoc
- [x] [Coding conventions](https://github.com/junit-team/junit5/blob/master/CONTRIBUTING.md#coding-conventions) (e.g. for logging) have been followed
- [x] Change is covered by [automated tests](https://github.com/junit-team/junit5/blob/master/CONTRIBUTING.md#tests) including corner cases, errors, and exception handling
- [x] Change is documented in the [User Guide](http://junit.org/junit5/docs/snapshot/user-guide/) and [Release Notes](http://junit.org/junit5/docs/snapshot/user-guide/#release-notes)
- [x] All [continuous integration builds](https://github.com/junit-team/junit5#continuous-integration-builds) pass

### CODE REVIEW

**Comment by sormuras** [comment]
Looks good so far -- only a `gradlew spotlessApply` run is missing to get the CI builds pass.

**Comment by juliette-derancourt** [comment]
> Looks good so far -- only a gradlew spotlessApply run is missing to get the CI builds pass.

Thanks! Should be better now :)

**Comment by juliette-derancourt** [comment]
I noticed something strange while doing this: the test `underscoreGenerator()` in [DisplayNameGenerationTests](https://github.com/junit-team/junit5/blob/b3ee93ff9e4ffe81a84bad04af5d9decb12d8161/junit-jupiter-engine/src/test/java/org/junit/jupiter/api/DisplayNameGenerationTests.java#L55) still passes if I leave the parentheses at the end of a display name.

It seems to be because of the implementation of [assertLinesMatch](https://github.com/junit-team/junit5/blob/b3ee93ff9e4ffe81a84bad04af5d9decb12d8161/junit-jupiter-api/src/main/java/org/junit/jupiter/api/Assertions.java#L1581), which is used here. This assertion internally relies on the `boolean matches(String regex)` method of `String.java`, which takes a regex and therefore ignore the `()` at the end.

Don't know if this matters or not?

**Comment by sormuras** [comment]
> Should be better now :)

Great. Looks good. Will merge it soon.

> [...] `assertLinesMatch` [...] which takes a regex and therefore ignore the `()` at the end.

Yes, that's the expected behaviour of this "staged-matching assertion utility". It's up to the test author to pass a stricter regex as an expected line to prevent "false-positives".

**Pull request merged**
