### PR TITLE
junit-platform-commons 1.7.0 does not contain MANIFEST.MF as first JAR entry (#2438)

### LINKED ISSUE #2438: junit-platform-commons 1.7.0 does not contain MANIFEST.MF as first JAR entry
While the JAR file specification doesn't mention this, the `java.util.jar.JarInputStream` implementation assumes that `META-INF/MANIFEST.MF` is the first or second entry in a jar file.

From the `JarInputStream` sources:
> // This implementation assumes the META-INF/MANIFEST.MF entry
> // should be either the first or the second entry (when preceded
> // by the dir META-INF/). It skips the META-INF/ and then
> // "consumes" the MANIFEST.MF to initialize the Manifest object.

Also the [Java Archive Tool Documentation](https://docs.oracle.com/javase/7/docs/technotes/tools/solaris/jar.html) mentions:

> The jar tool automatically generates a manifest file entry named META-INF/MANIFEST.MF. It is always the first entry in the jar file. 

Commit 5631ebc (#2217) introduced reproducible builds. Part of this is `java-repackage-jars` plugin, which sorts jar entries alphabetically. For junit-platform-commons, this results in the following first entries:

> META-INF/
> META-INF/LICENSE-notice.md
> META-INF/LICENSE.md
> META-INF/MANIFEST.MF

Evidently, this causes issues with any tools implemented using `JarInputStream`.

## Steps to reproduce

- download [junit-platform-commons-1.7.0.jar](https://search.maven.org/remotecontent?filepath=org/junit/platform/junit-platform-commons/1.7.0/junit-platform-commons-1.7.0.jar)
- `unzip -l junit-platform-commons-1.7.0.jar` (or list the file contents in another way)

Note: my real scenario involved [code in an Apache Sling module](https://github.com/apache/sling-org-apache-sling-installer-core/blob/master/src/main/java/org/apache/sling/installer/core/impl/Util.java#L74)

## Desired outcome

It would be nice if `MANIFEST.MF` could be sorted to the top of the list for reproducible builds.

### PR DESCRIPTION
**Pull request by jsedding**
Resolves  #2438

## Overview

- always sort "META-INF/" and "META-INF/MANIFEST.MF" entries first

---

I hereby agree to the terms of the [JUnit Contributor License Agreement](https://github.com/junit-team/junit5/blob/002a0052926ddee57cf90580fa49bc37e5a72427/CONTRIBUTING.md#junit-contributor-license-agreement).

---

### Definition of Done

- [x] There are no TODOs left in the code
- [x] Method [preconditions](https://junit.org/junit5/docs/snapshot/api/org.junit.platform.commons/org/junit/platform/commons/util/Preconditions.html) are checked and documented in the method's Javadoc
- [x] [Coding conventions](https://github.com/junit-team/junit5/blob/HEAD/CONTRIBUTING.md#coding-conventions) (e.g. for logging) have been followed
- [x] Change is covered by [automated tests](https://github.com/junit-team/junit5/blob/HEAD/CONTRIBUTING.md#tests) including corner cases, errors, and exception handling
- [x] Public API has [Javadoc](https://github.com/junit-team/junit5/blob/HEAD/CONTRIBUTING.md#javadoc) and [`@API` annotations](https://apiguardian-team.github.io/apiguardian/docs/current/api/org/apiguardian/api/API.html)
- [x] Change is documented in the [User Guide](https://junit.org/junit5/docs/snapshot/user-guide/) and [Release Notes](https://junit.org/junit5/docs/snapshot/user-guide/#release-notes)
- [x] All [continuous integration builds](https://github.com/junit-team/junit5#continuous-integration-builds) pass

### CODE REVIEW

**Comment by sormuras** [comment]
This error

https://github.com/junit-team/junit5/pull/2442/checks?check_run_id=1214197418#step:7:703

is not related to your changes. Seems to be a Gradle 6.7-rc-3 issue that @marcphilipp already passed along.

**Review by sormuras — CHANGES_REQUESTED** [review]
LGTM over all.

An integration test that ensures `META-INF/` is the first and `META-INF/MANIFEST.MF` is the second entry is missing. Please add such a new test into `platform-tooling-support-tests`, right next to `JarDescribeModuleTests.java`.

**Comment by jsedding** [comment]
Thanks for the pointers @sormuras. I have added a test and verified that it fails before the changes contained in the PR.

**Review by sormuras — APPROVED** [review]

**Comment by sormuras** [comment]
Thank you Julian!

**Pull request merged**
