### PR TITLE
Update Asciidoctor instructions

### PR DESCRIPTION
**Pull request by halitanildonmez**
…f the user guide

## Overview

Hello! I was taking a look at this issue: https://github.com/junit-team/junit5/issues/2315 and I was trying to generate the pdf 
version of the user guide. I had to look around a bit and noticed that the readme was missing information on generating the pdf 
report.
I am actually tacking the issue #2315 now but thought that it would be good to update the readme. Also some outdated stuff
---

I hereby agree to the terms of the [JUnit Contributor License Agreement](https://github.com/junit-team/junit5/blob/002a0052926ddee57cf90580fa49bc37e5a72427/CONTRIBUTING.md#junit-contributor-license-agreement).

---

### Definition of Done

- [ ] There are no TODOs left in the code
- [ ] Method [preconditions](https://junit.org/junit5/docs/snapshot/api/org.junit.platform.commons/org/junit/platform/commons/util/Preconditions.html) are checked and documented in the method's Javadoc
- [ ] [Coding conventions](https://github.com/junit-team/junit5/blob/HEAD/CONTRIBUTING.md#coding-conventions) (e.g. for logging) have been followed
- [ ] Change is covered by [automated tests](https://github.com/junit-team/junit5/blob/HEAD/CONTRIBUTING.md#tests) including corner cases, errors, and exception handling
- [ ] Public API has [Javadoc](https://github.com/junit-team/junit5/blob/HEAD/CONTRIBUTING.md#javadoc) and [`@API` annotations](https://apiguardian-team.github.io/apiguardian/docs/current/api/org/apiguardian/api/API.html)
- [ ] Change is documented in the [User Guide](https://junit.org/junit5/docs/snapshot/user-guide/) and [Release Notes](https://junit.org/junit5/docs/snapshot/user-guide/#release-notes)
- [ ] All [continuous integration builds](https://github.com/junit-team/junit5#continuous-integration-builds) pass

### CODE REVIEW

**Comment by marcphilipp** [comment]
Thanks for noticing! Please fix the formatting issues so we can merge this.

**Comment by halitanildonmez** [comment]
I think I fixed the indentation issue ? Am I missing something ?

**Comment by marcphilipp** [comment]
Apparently there's still a formatting issue. Please run `./gradlew :spotlessApply`.

**Comment by halitanildonmez** [comment]
I ran and pushed it. Hope it is better ?

**Comment by marcphilipp** [comment]
Thanks, @halitanildonmez! 👍

**Comment by halitanildonmez** [comment]
you are most welcome! Thank you for taking the time to review this

**Pull request merged**
