### PR TITLE
Add CamelCase Display Name Generator

### PR DESCRIPTION
**Pull request by zoltanersek**
Issue: #1595

## Overview

Please describe your changes here and list any open questions you might have.

---

I hereby agree to the terms of the [JUnit Contributor License Agreement](https://github.com/junit-team/junit5/blob/002a0052926ddee57cf90580fa49bc37e5a72427/CONTRIBUTING.md#junit-contributor-license-agreement).

---

### Definition of Done

- [x] There are no TODOs left in the code
- [ ] Method [preconditions](http://junit.org/junit5/docs/snapshot/api/org/junit/platform/commons/util/Preconditions.html) are checked and documented in the method's Javadoc
- [ ] [Coding conventions](https://github.com/junit-team/junit5/blob/master/CONTRIBUTING.md#coding-conventions) (e.g. for logging) have been followed
- [ ] Change is covered by [automated tests](https://github.com/junit-team/junit5/blob/master/CONTRIBUTING.md#tests) including corner cases, errors, and exception handling
- [ ] Public API has [Javadoc](https://github.com/junit-team/junit5/blob/master/CONTRIBUTING.md#javadoc) and [`@API` annotations](http://junit.org/junit5/docs/snapshot/api/org/junit/platform/commons/meta/API.html)
- [ ] Change is documented in the [User Guide](http://junit.org/junit5/docs/snapshot/user-guide/) and [Release Notes](http://junit.org/junit5/docs/snapshot/user-guide/#release-notes)
- [x] All [continuous integration builds](https://github.com/junit-team/junit5#continuous-integration-builds) pass

### CODE REVIEW

**Comment by zoltanersek** [comment]
Any comments here ?

**Comment by sormuras** [comment]
No comments, yet. Planning to review this and #1609 after 5.4-M1 is released.

**Comment by marcphilipp** [comment]
Blocked due to https://github.com/junit-team/junit5/issues/1595#issuecomment-513181707.

**Comment by hjohn** [comment]
Hm... how about this tiny implementation:

```import org.junit.jupiter.api.DisplayNameGenerator;

public class ReplaceCamelCaseDisplayNameGenerator implements DisplayNameGenerator {
  private static final Pattern UPPERCASE_LETTER = Pattern.compile("([A-Z]|[0-9]+)");

  @Override
  public String generateDisplayNameForClass(Class<?> testClass) {
    return toName(testClass.getSimpleName() + "...");
  }

  @Override
  public String generateDisplayNameForNestedClass(Class<?> nestedClass) {
    return toName(nestedClass.getSimpleName() + "...");
  }

  @Override
  public String generateDisplayNameForMethod(Class<?> testClass, Method testMethod) {
    return toName(testMethod.getName());
  }

  private static String toName(String text) {
    return text.substring(0, 1).toUpperCase()
      + UPPERCASE_LETTER.matcher(text.substring(1)).replaceAll(mr -> " " + (mr.group(1).toLowerCase()));
  }
}```

**Comment by marcphilipp** [comment]
Closing with the rationale explained in https://github.com/junit-team/junit5/issues/1595#issuecomment-607828035.

**Pull request closed without merging**
