### PR TITLE
IncludeTags and excludeTags accept empty strings

### PR DESCRIPTION
**Pull request by VikasSherawat**
Issue: #1126

## Overview

IncludeTags and ExcludeTags are modified to accept empty strings as input parameter.

---

I hereby agree to the terms of the JUnit Contributor License Agreement.

---

### Definition of Done

- [x] There are no TODOs left in the code
- [x] Method [preconditions](http://junit.org/junit5/docs/snapshot/api/org/junit/platform/commons/util/Preconditions.html) are checked and documented in the method's Javadoc
- [x] [Coding conventions](https://github.com/junit-team/junit5/blob/master/CONTRIBUTING.md#coding-conventions) (e.g. for logging) have been followed
- [x] Change is covered by [automated tests](https://github.com/junit-team/junit5/blob/master/CONTRIBUTING.md#tests)
- [x] Public API has [Javadoc](https://github.com/junit-team/junit5/blob/master/CONTRIBUTING.md#javadoc) and [`@API` annotations](http://junit.org/junit5/docs/snapshot/api/org/junit/platform/commons/meta/API.html)
- [x] Change is documented in the [User Guide](http://junit.org/junit5/docs/snapshot/user-guide/) and [Release Notes](http://junit.org/junit5/docs/snapshot/user-guide/#release-notes)
- [x] All [continuous integration builds](https://github.com/junit-team/junit5#continuous-integration-builds) pass

### CODE REVIEW

**Comment by sbrannen** [comment]
I'm not convinced that we should remove the "not empty" validation entirely from the Platform.

Rather, I think it may be better to "ignore" (and not register) empty tags within the Surefire Provider and Gradle plugin.

@junit-team/junit-lambda Thoughts?

**Comment by sbrannen** [comment]
In any case, it does **not** make sense to actually register an empty tag.

So we cannot accept the PR _as is_.

**Comment by sbrannen** [comment]
If an empty tag is supplied and ignored, the Platform should log such cases.

**Comment by marcphilipp** [comment]
> Rather, I think it may be better to "ignore" (and not register) empty tags within the Surefire Provider and Gradle plugin.

I quite agree. I think this should be done in `JUnitPlatformProvider` instead.

**Comment by VikasSherawat** [comment]
@sbrannen @marcphilipp 
Thanks for the valuable comments.!! I'll try to understand JUnitPlatformProvider class and make changes accordingly.

**Comment by marcphilipp** [comment]
I think it boils down to changing the following line to use `StringUtils.isNotBlank()` and writing tests for it.

https://github.com/junit-team/junit5/blob/master/junit-platform-surefire-provider/src/main/java/org/junit/platform/surefire/provider/JUnitPlatformProvider.java#L185

**Comment by VikasSherawat** [comment]
@marcphilipp @sbrannen did i address the issue in right way?

**Comment by VikasSherawat** [comment]
@marcphilipp should i document these changes in the Release notes?

**Comment by marcphilipp** [comment]
@VikasSherawat Yes, that would be great!

**Comment by marcphilipp** [comment]
Thanks, @VikasSherawat!

**Pull request closed without merging**
