### PR TITLE
JUnit 5 Theories

### PR DESCRIPTION
**Pull request by nrllewellyn**
## Overview

(Re-opening as a separate pull request, since first PR was corrupted by a botched Git rebase.)

Adds theories, in a form similar to JUnit 4's Theories. This will close ticket #395.

Substantial changes from JUnit 4:

- Methods allowed as sources of data points
- Streams and Iterators as accepted data point types, but only when produced by methods (since both are stateful, they have to come from a method so they can be read more than once)
- Suppliers system for simple data points (similar in form to parameterized tests, but allows mixing of in-line data points with class-level data points)
  - Specified via the `ArgumentsSuppliedBy` meta-annotation. This ties the annotation to a supplier class
  - Supplier class implements `TheoryArgumentSupplier` (or extends `AbstractTheoryArgumentSupplier` for common use cases). This class reads the annotation and produces the corresponding data points
  - Examples:
```
@Theory
public void myTheory(@IntValues(0, 42, 99) int someIntValue)

@Theory
public void myTheory(@ByteValues(0, 42) byte somByteValue, SomeClass valueFromClassLevelDataPoint)
```
- Qualifiers directly on theory parameters. Example:
```
@DataPoints(qualifiers = "nonZero")
private static final List<Double> GREATER_THAN_ZERO = Arrays.asList(3, 5, 7);

@DataPoint
private static final Double ZERO = 0;

@DataPoint(qualifiers = "nonZero")
private static final double NEGATIVE_NUMBER =  -4;

@Theory
public void testDivisionOperator(double dividend, @Qualifiers("nonZero") double divisor)
```

A few (very rough) examples can be found in:
junit-jupiter-theories/src/test/java/org/junit/jupiter/theories/TheoriesTestCase.java

---

I hereby agree to the terms of the [JUnit Contributor License Agreement](https://github.com/junit-team/junit5/blob/master/CONTRIBUTING.md#junit-contributor-license-agreement).

---

### Definition of Done

- [X] There are no TODOs left in the code
- [X] Method [preconditions](http://junit.org/junit5/docs/snapshot/api/org/junit/platform/commons/util/Preconditions.html) are checked and documented in the method's Javadoc
- [X] [Coding conventions](https://github.com/junit-team/junit5/blob/master/CONTRIBUTING.md#coding-conventions) (e.g. for logging) have been followed
- [X] Change is covered by [automated tests](https://github.com/junit-team/junit5/blob/master/CONTRIBUTING.md#tests)
- [X] Public API has [Javadoc](https://github.com/junit-team/junit5/blob/master/CONTRIBUTING.md#javadoc) and [`@API` annotations](http://junit.org/junit5/docs/snapshot/api/org/junit/platform/commons/meta/API.html)
- [x] Change is documented in the [User Guide](http://junit.org/junit5/docs/snapshot/user-guide/) and [Release Notes](http://junit.org/junit5/docs/snapshot/user-guide/#release-notes)
- [x] All [continuous integration builds](https://github.com/junit-team/junit5#continuous-integration-builds) pass

### CODE REVIEW

**Comment by marcphilipp** [comment]
@nrllewellyn Thanks for the PR! Before doing a detailed review, I wanted to let you know that we discussed whether or not we want to maintain a Theories equivalent in the JUnit 5 codebase in the JUnit 5 team. We've come to the conclusion that property-based testing may be better off in a custom test engine instead of in Jupiter. For example, @jlink has written [JQwik](http://jqwik.net/) which already supports a lot more features than JUnit 4's theories, e.g. shrinking, not reporting every invocation separately (as `TestTemplates` do) etc. If you feel passionate enough to maintain this extension as a stand-alone project, I'd be happy to give you feedback on the implementation. If you do, please add it to the [wiki page](https://github.com/junit-team/junit5/wiki/Third-party-Extensions). However, please understand that we don't want to include it into JUnit core at this point.

**Comment by nrllewellyn** [comment]
@marcphilipp  Thanks for the detailed info. Perhaps my team uses Theories differently than they were originally intended--we always used them as parameterized tests with "try all combinations of parameters" functionality, whereas JQwik seems to focus more on random data.

That said, it's obviously your team's call on what you let into your library. :-)

Thanks for the offer of the code review. Let me read up a bit more on JQwik and some of the other available extensions first--I don't want to overlap too much with what's already available. I'll get back to you if I want to go ahead with maintaining it as a separate library.

**Comment by marcphilipp** [comment]
The fact that @sormuras also recently has written a sample [`CartesianProductProvider`](https://github.com/junit-team/junit5-samples/blob/master/junit5-jupiter-extensions/src/main/java/com/example/cartesian/CartesianProductProvider.java) extension is another indication that there seems to be a need for something like that. I think this could be addressed by a `ArgumentsProvider` implementation for `@ParameterizedTests`, e.g. one that collects data points from fields methods.

**Comment by sormuras** [comment]
Sounds like a plan.

**Comment by marcphilipp** [comment]
I've created #1427. Let's continue the discussion there.

**Comment by mxmlnglt** [comment]
> The fact that @sormuras also recently has written a sample [`CartesianProductProvider`](https://github.com/junit-team/junit5-samples/blob/master/junit5-jupiter-extensions/src/main/java/com/example/cartesian/CartesianProductProvider.java) extension...

404... the class now resides at [CartesianProductProvider.java](https://github.com/junit-team/junit-examples/blob/main/junit-jupiter-extensions/src/main/java/com/example/cartesian/CartesianProductProvider.java) 😉

**Pull request closed without merging**
