### PR TITLE
selectively execute arguments from method source using only

### PR DESCRIPTION
**Pull request by signed**
## Overview

Debugging a single case of a parameterized test is quiet cumbersome. To make this easier this pull requests adds a new factory method `only` on `Arguments`.

As soon as at least a single Argument in a `MethodSource` is flagged as `only` only those are executed. If no Argument is flagged with `only` all elements of the MethodSource are executed.

---

I hereby agree to the terms of the JUnit Contributor License Agreement.

---

### Definition of Done

- [x] There are no TODOs left in the code
- [x] Method [preconditions](http://junit.org/junit5/docs/snapshot/api/org/junit/platform/commons/util/Preconditions.html) are checked and documented in the method's Javadoc
- [x] [Coding conventions](https://github.com/junit-team/junit5/blob/master/CONTRIBUTING.md#coding-conventions) (e.g. for logging) have been followed
- [x] Change is covered by [automated tests](https://github.com/junit-team/junit5/blob/master/CONTRIBUTING.md#tests)
- [x] Public API has [Javadoc](https://github.com/junit-team/junit5/blob/master/CONTRIBUTING.md#javadoc) and [`@API` annotations](http://junit.org/junit5/docs/snapshot/api/org/junit/platform/commons/meta/API.html)
- [ ] Change is documented in the [User Guide](http://junit.org/junit5/docs/snapshot/user-guide/) and [Release Notes](http://junit.org/junit5/docs/snapshot/user-guide/#release-notes)
- [ ] All [continuous integration builds](https://github.com/junit-team/junit5#continuous-integration-builds) pass

### CODE REVIEW

**Comment by marcphilipp** [comment]
Interesting idea, thanks for the PR!

To be honest, I think we should rather fix #1025 instead of introducing a workaround that only works for `@MethodSource`.

@junit-team/junit-lambda Thoughts?

**Comment by signed** [comment]
The linked issue seems to be about re-running failed tests.
In my case I want to run a single Argument without having to run all Arguments first.

Or is there a way for the IDE to derive the unique id without running all Arguments first?

**Comment by marcphilipp** [comment]
> In my case I want to run a single Argument without having to run all Arguments first.

Understood. Any ideas how to make this more generally useful besides `@MethodSource`?

> Or is there a way for the IDE to derive the unique id without running all Arguments first?

Nope, since these are dynamic descriptors, the IDE cannot discover them before execution.

**Comment by sbrannen** [comment]
> To be honest, I think we should rather fix #1025 instead of introducing a workaround that only works for `@MethodSource`.

I agree with @marcphilipp on this one.

The typical developer follows the following steps:

1. run parameterized test.
2. it fails for a given invocation.
3. re-run the single invocation (covered by #1025) in _debug_ mode.

Thus, there is no need to pick a particular invocation in advance (i.e., before having seen that it even fails).

I therefore propose that we close this issue.

**Comment by sormuras** [comment]
> I therefore propose that we close this issue.

+1

**Comment by sbrannen** [comment]
**Team Decision**:

Since the typical developer workflow follows the steps outlined in https://github.com/junit-team/junit5/pull/1228#issuecomment-356294389, we have decided to respectfully decline this PR.

**Pull request closed without merging**
