### PR TITLE
add micro tests for MethodInvoker

### PR DESCRIPTION
**Pull request by signed**
## Microtests for MethodInvoker
see #142

---

I hereby agree to the terms of the JUnit Contributor License Agreement.

### CODE REVIEW

**Comment by sbrannen** [comment]
_in progress_ (as in... I'm reviewing the PR)

**Comment by sbrannen** [comment]
Great work!

I like your DSL-style of testing, and... the _full logging_ extension is quite cool! 👍 

Have a look at my _Polishing_ commit to see how I revised `@FullLogging` and _embedded_ the extension implementation.

Oh yeah, this has been merged into `master` in 3ebaf5fc328931679943bb55a4007a64d5cf7b85.

**Comment by signed** [comment]
Nice way to get rid of `@ExtendWith({ FullLogging.class })` on each test, thx for sharing.

`MethodInvokerTests:36` @FullLogging is commented out, intended?
`FullLogging:50` `static` at Extension class can be deleted, it is the default.

**Comment by sbrannen** [comment]
> Nice way to get rid of `@ExtendWith({ FullLogging.class })` on each test, thx for sharing.

You're welcome!

And yeah... that's a little known feature, but I think people will begin to catch on to it.

> `MethodInvokerTests:36` @FullLogging is commented out, intended?

Yes. I intend to use `@FullLogging` as a means for _debugging_ while I'm authoring a test, but once the test is committed, I'd prefer not to have the logging. It's a matter of taste in the end.

> `FullLogging:50` `static` at Extension class can be deleted, it is the default.

Ah, yes. Thanks for pointing that out; I'll delete `static`.

**Pull request merged**
