### PR TITLE
Refine the user guide and example

### PR DESCRIPTION
**Pull request by oohira**
I'm not sure which is appropriate English, `larger number` or `bigger number` ;-p

---

I hereby agree to the terms of the [JUnit Contributor License Agreement](https://github.com/junit-team/junit5/blob/002a0052926ddee57cf90580fa49bc37e5a72427/CONTRIBUTING.md#junit-contributor-license-agreement).

### CODE REVIEW

**Comment by jbduncan** [comment]
@oohira Hmm. Even though I'm a native speaker, I'm actually not sure which one is more grammatically correct (if any one of them can be considered more "correct" than the other)!

To my mind, "larger number" reads better than "bigger number".

Do we have any grammarians here who can clarify things? :)

**Comment by sbrannen** [comment]
I think "larger value" is perfectly fine in this scenario.

In any case, you can see that this question has been asked numerous times on [the Internet](https://www.google.com/search?q=larger+number+or+bigger+number&ie=utf-8&oe=utf-8). 😉

**Comment by sbrannen** [comment]
This has been merged into `master`.

Thanks

**Comment by jbduncan** [comment]
Cool, thanks for sharing your research regarding "larger value" with us @sbrannen. :)

**Comment by oohira** [comment]
@jbduncan @sbrannen Thanks for your comments!

**Pull request merged**
