### PR TITLE
Fix conditional link to PDF download in documentation

### PR DESCRIPTION
**Pull request by joel-costigliola**
## Overview

Fix conditional link to PDF download

---

I hereby agree to the terms of the [JUnit Contributor License Agreement](https://github.com/junit-team/junit5/blob/002a0052926ddee57cf90580fa49bc37e5a72427/CONTRIBUTING.md#junit-contributor-license-agreement).

---

### Definition of Done

None of the items below are really applicable to a simple documentation typo so I'm not sure what to do with them. 

- [ ] There are no TODOs left in the code
- [ ] Method [preconditions](http://junit.org/junit5/docs/snapshot/api/org/junit/platform/commons/util/Preconditions.html) are checked and documented in the method's Javadoc
- [ ] [Coding conventions](https://github.com/junit-team/junit5/blob/master/CONTRIBUTING.md#coding-conventions) (e.g. for logging) have been followed
- [ ] Change is covered by [automated tests](https://github.com/junit-team/junit5/blob/master/CONTRIBUTING.md#tests) including corner cases, errors, and exception handling
- [ ] Public API has [Javadoc](https://github.com/junit-team/junit5/blob/master/CONTRIBUTING.md#javadoc) and [`@API` annotations](http://junit.org/junit5/docs/snapshot/api/org/junit/platform/commons/meta/API.html)
- [ ] Change is documented in the [User Guide](http://junit.org/junit5/docs/snapshot/user-guide/) and [Release Notes](http://junit.org/junit5/docs/snapshot/user-guide/#release-notes)
- [ ] All [continuous integration builds](https://github.com/junit-team/junit5#continuous-integration-builds) pass

### CODE REVIEW

**Comment by sbrannen** [comment]
Hmmmm.... 

The status quo seems to be fine to me:

https://junit.org/junit5/docs/snapshot/user-guide/

That's the HTML version of the User Guide that links to the PDF version.

And [PDF version](https://junit.org/junit5/docs/snapshot/user-guide/index.pdf), does **not** link to the PDF version, which is the intended behavior.

What exactly are you trying to "fix"? 😉

**Comment by joel-costigliola** [comment]
The link should not be shown if the pdf documentation has not been generated.

I might be wrong but I believe the pdf version is generated because of `backends 'html5', 'pdf'` that includes `'pdf'` (see  
https://github.com/junit-team/junit5/blob/master/documentation/documentation.gradle#L107).

If you were to change that setting to `backends 'html5'` the generated html documentation would still display the link to the pdf but it would be broken since no pdf has been generated.

I actually have cloned the junit5 repo to start a user guide for assertj (wip as you can see here https://assertj.github.io/doc/#release-notes :grinning:) and I stumbled upon this "issue" as I'm not generating any pdf at the moment but still have a link to a non existent pdf.

**Comment by joel-costigliola** [comment]
I see your point, the correct logic would be too only include the pdf link in the HTML version when the pdf has been generated but my change doesn't quite do that.

Looking at https://github.com/asciidoctor/asciidoctor.org/blob/master/docs/_includes/conditional-preprocessor-directives.adoc it does not seem easy to express that condition.

**Comment by sbrannen** [comment]
Glad you sorted it out. 😉

**Pull request closed without merging**
