### PR TITLE
Rename file to match class name

### PR DESCRIPTION
**Pull request by piefel**
## Overview

There’s a bug in the source: The file 
`junit-platform-console/src/main/java/org/junit/platform/console/options/URIConverter.java`
contains the class `org.junit.platform.console.options.UriConverter` –

---

I hereby agree to the terms of the [JUnit Contributor License Agreement](https://github.com/junit-team/junit5/blob/002a0052926ddee57cf90580fa49bc37e5a72427/CONTRIBUTING.md#junit-contributor-license-agreement).

---

### Definition of Done

- [ ] There are no TODOs left in the code
- [ ] Method [preconditions](http://junit.org/junit5/docs/snapshot/api/org/junit/platform/commons/util/Preconditions.html) are checked and documented in the method's Javadoc
- [ ] [Coding conventions](https://github.com/junit-team/junit5/blob/master/CONTRIBUTING.md#coding-conventions) (e.g. for logging) have been followed
- [ ] Change is covered by [automated tests](https://github.com/junit-team/junit5/blob/master/CONTRIBUTING.md#tests)
- [ ] Public API has [Javadoc](https://github.com/junit-team/junit5/blob/master/CONTRIBUTING.md#javadoc) and [`@API` annotations](http://junit.org/junit5/docs/snapshot/api/org/junit/platform/commons/meta/API.html)
- [ ] Change is documented in the [User Guide](http://junit.org/junit5/docs/snapshot/user-guide/) and [Release Notes](http://junit.org/junit5/docs/snapshot/user-guide/#release-notes)
- [ ] All [continuous integration builds](https://github.com/junit-team/junit5#continuous-integration-builds) pass

### CODE REVIEW

**Comment by marcphilipp** [comment]
Good catch, thanks! 👍

**Comment by jbduncan** [comment]
I remember submitting a PR for a similar fix with a similarly-named file a few months ago, so indeed, good catch @piefel! :+1:

**Comment by piefel** [comment]
It seems everbody on the team is using MacOS these days. (Or even Windows.)

**Comment by marcphilipp** [comment]
Even though it’s (at least in this case) not technically a bug because the class was not public, it would be useful to have an automated check in place. Any ideas? Does Checkstyle support that?

**Comment by sbrannen** [comment]
> Even though it’s (at least in this case) not technically a bug because the class was not public, 

Right: definitely not a "bug" but potentially misleading nonetheless.

> it would be useful to have an automated check in place. 

I agree it would be useful to have some sort of automated check. Though I guess it would only make sense if the Java source file contains a single, non-public type.

> Any ideas? Does Checkstyle support that?

Dunno... 🤷🏻‍♂️

**Comment by piefel** [comment]
I don’t know about your ‘bug’ definition, but JUnit 5 refused to be compiled on a Linux machine using an Oracle JDK, and that looks pretty much like a bug to me.

**Comment by sbrannen** [comment]
JUnit 5 has CI builds on Linux and Windows (and macOS as well I believe).

- https://junit.ci.cloudbees.com/job/JUnit5/job/master/
- https://travis-ci.org/junit-team/junit5
- https://ci.appveyor.com/project/marcphilipp/junit5/branch/master

The last time I checked it's not a requirement of a Java source file to have a name that matches a non-public type declared in that file as long as the file does not declare any top-level public type.

Thus it would appear that it is a _bug_ with the compiler you used.

Did you compile from the command line with the Gradle build?

Or did you compile in an IDE, and if so which one?

**Comment by sbrannen** [comment]
> Thus it would appear that it is a _bug_ with the compiler you used.

OK. I retract that. 😉 

It turns out that compilers are not required to enforce that a type name match the file name. Rather, it is an "option" in certain circumstances.

Specifically, Section  ["7.6. Top Level Type Declarations"](https://docs.oracle.com/javase/specs/jls/se8/html/jls-7.html#jls-7.6) of the JLS states the following.

> If and only if packages are stored in a file system (§7.2), the host system may choose to enforce the restriction that it is a compile-time error if a type is not found in a file under a name composed of the type name plus an extension (such as .java or .jav) if either of the following is true:
> 
> - The type is referred to by code in other compilation units of the package in which the type is declared.
> - The type is declared public (and therefore is potentially accessible from code in other packages).

The compilers used by all CI builds, core committers, and contributors thus far have never enforced the optional first condition mentioned above.

Thus, we simply never ran into this situation.

Given that, @piefel, we would be very interested in knowing exactly how you encountered this situation (i.e., Gradle build, IDE, JDK version, OS version, etc.).

**Comment by sbrannen** [comment]
FYI: I added the 🐛 label.

**Comment by piefel** [comment]
OK, there you got me. I copied over parts of the repo in an attempt to use the TreePrinter as an execution listener, and compiled my project using Maven and Java 8. I didn’t use the full JUnit build. Using the command line directly works and does _not_ enforce the file name. I wonder wether the maven-compiler-plugin tightens the configuration.

BTW, the build does not work anymore with Java 9, or at least 9.0.4: There is a warning about a missing `serialVersionUID` in `UriSource` (which is an interface, BTW). Well, Java 9 is outdated anyway, but `settings.gradle` asks for Java 9 or higher.

**Comment by sbrannen** [comment]
> I wonder wether the maven-compiler-plugin tightens the configuration.

Perhaps...

**Comment by sbrannen** [comment]
> BTW, the build does not work anymore with Java 9, or at least 9.0.4: There is a warning about a missing `serialVersionUID` in `UriSource` (which is an interface, BTW). Well, Java 9 is outdated anyway, but `settings.gradle` asks for Java 9 or higher.

Thanks for mentioning that.

@sormuras actually just ran into that issue as well and added a pseudo-fix in commit ae40f6e123ebd4cb3a2ad7020a427b4e9bd120c5 for use with JitPack.

We think it must be a bug in the compiler, but we have not yet investigated that further.

In any case, I think I'll update `settings.gradle` to enforce JDK 10 for all builds now as a result.

**Comment by sbrannen** [comment]
Regarding the compiler warning for `UriSource`, it would appear that it is due to the fact that we recently introduced a `static` factory method in `UriSource`, and that would appear to be related to the following JDK bug:

https://bugs.openjdk.java.net/browse/JDK-8191637

That bug was fixed in JDK 10.0.1 and 11 EA.

**Comment by sbrannen** [comment]
Further discussion on that "`Serializable` for interfaces" bug: https://stackoverflow.com/questions/47390432/functional-interface-with-default-behavior-with-serializable#comment83187695_47390432

**Comment by sbrannen** [comment]
FYI: the Gradle build now requires JDK 10 or higher: 545e4d9f7ddb1722a90542eb506b3991b3a9ae14

**Comment by sbrannen** [comment]
FWIW, the `README` had already documented the JDK 10+ requirement: https://github.com/junit-team/junit5#building-from-source

**Comment by sormuras** [comment]
> FWIW, the README had already documented the JDK 10+ requirement: https://github.com/junit-team/junit5#building-from-source

Aye. GA 5.2 was already built with 10.0.1 -- only left the option to build with 9 for our Eclipse users. :-)

**Pull request merged**
