### PR TITLE
Fix link to section about parallel execution

### PR DESCRIPTION
**Pull request by sivaraam**
## Overview
Fixes a broken link to a section about parallel execution.

---

I hereby agree to the terms of the [JUnit Contributor License Agreement](https://github.com/junit-team/junit5/blob/002a0052926ddee57cf90580fa49bc37e5a72427/CONTRIBUTING.md#junit-contributor-license-agreement).

---

### Definition of Done

- [ ] There are no TODOs left in the code
- [ ] Method [preconditions](https://junit.org/junit5/docs/snapshot/api/org/junit/platform/commons/util/Preconditions.html) are checked and documented in the method's Javadoc
- [ ] [Coding conventions](https://github.com/junit-team/junit5/blob/master/CONTRIBUTING.md#coding-conventions) (e.g. for logging) have been followed
- [ ] Change is covered by [automated tests](https://github.com/junit-team/junit5/blob/master/CONTRIBUTING.md#tests) including corner cases, errors, and exception handling
- [ ] Public API has [Javadoc](https://github.com/junit-team/junit5/blob/master/CONTRIBUTING.md#javadoc) and [`@API` annotations](https://apiguardian-team.github.io/apiguardian/docs/current/api/org/apiguardian/api/API.html)
- [ ] Change is documented in the [User Guide](https://junit.org/junit5/docs/snapshot/user-guide/) and [Release Notes](https://junit.org/junit5/docs/snapshot/user-guide/#release-notes)
- [ ] All [continuous integration builds](https://github.com/junit-team/junit5#continuous-integration-builds) pass

### CODE REVIEW

**Comment by sormuras** [comment]
The current link works.

From: https://junit.org/junit5/docs/current/user-guide/#running-tests-capturing-output 
To: https://junit.org/junit5/docs/current/user-guide/#writing-tests-parallel-execution

image

Which error do you see on your side?

**Comment by sbrannen** [comment]
I think @sivaraam is possibly referring to the fact that cross-document links do not work when viewing Asciidoc files on GitHub. For example:

https://github.com/junit-team/junit5/blob/master/documentation/src/docs/asciidoc/user-guide/running-tests.adoc

If you scroll to the bottom of the document and click the link, it links to:

https://github.com/junit-team/junit5/blob/master/documentation/src/docs/asciidoc/user-guide/running-tests.adoc#writing-tests-parallel-execution

And that doesn't exist within the same document.

@sivaraam, can you please confirm that's what you're referring to?

In any case, please note that we do not support proper cross-document linking on GitHub: our links are implemented to work with the generated documentation as @sormuras pointed out.

**Comment by sivaraam** [comment]
> @sivaraam, can you please confirm that's what you're referring to?

Yes, you are correct.

> In any case, please note that we do not support proper cross-document linking on GitHub: our links are implemented to work with the generated documentation as @sormuras pointed out.

Ok, I get that. Just wondering, does this change break the linking in the generated documentation? I tried to generate the docs locally but faced issues during the Gradle build. I'll see if I could somehow make the build work.

**Comment by sivaraam** [comment]
I managed to build the HTML for the user guide from the asciidoc using Gradle. This change does seem to be breaking the links in the generated doc. So, I think it's better close this.

Anyways, thanks for the guidance 🙂

**Comment by sbrannen** [comment]
Thanks for the feedback, @sivaraam.

**Pull request closed without merging**
