### PR TITLE
Add assertEquals for primitive types

### LINKED ISSUE #110: Add overloaded assertEquals methods for primitive types

### PR DESCRIPTION
**Pull request by hotchemi**
## Overview

- This pr fixes #110 .
- I just added assetEquals for following primitive types.
  - byte
  - short
  - int
  - long
  - char
  - float
  - double

---

I hereby agree to the terms of the JUnit Contributor License Agreement.

### CODE REVIEW

**Comment by bechte** [comment]
Thank you for the pull request. Would you please add additional tests for values that are not equal, as well as tests for the calls to assertEquals(int,int,String) and assertEquals(int,int,Supplier<String>) accordingly? Please see the tests for the other methods. Thanks.

**Comment by hotchemi** [comment]
@bechte 
Thx, I added test cases.
One point I'd like to confirm is that I use `org.junit.gen5.api.Assertions#failNotEqual` internal assertion but is it good design? failNotEqual converts primitive arguments to String so it might take a cost than normal primitive comparison.

**Comment by bechte** [comment]
@hotchemi: Actually, for the assertion you use the int primitives. `failNotEqual` is only called in case of this comparison fails. I don't think it is a tremendous overhead, especially because Integers are being cached and the auto-boxing feature makes use of this cache. Plus, this only happens for failing tests. So, I don't have any concerns in this directions.

**Comment by bechte** [comment]
@hotchemi: Thanks for adding the tests. I think the `int` case is ready to be merged. Would it be possible for you to also add support for other primitive types as of #110 ? That would be great. If not, we probably merge this PR together with the changes from #110 .

**Comment by hotchemi** [comment]
@bechte Sure. I'll add another methods and test cases on this pull request tonight. So changed the title to work in progress. Thank you for your review.

**Comment by hotchemi** [comment]
@bechte I added following types of methods. Could you review?

- byte
- short
- int
- long
- char
- float
- double

**Comment by sbrannen** [comment]
@hotchemi, the work now looks complete. Thanks!

Before we merge it, however, can you please squash all commits into a single commit (e.g., via `git rebase --interactive --autosquash`) and force push your changes for this PR?

**Comment by hotchemi** [comment]
@sbrannen Did it. Sure :smile:

**Comment by sbrannen** [comment]
@hotchemi, thanks!

We will merge this in the near future.

**Comment by hotchemi** [comment]
:bow:

**Pull request merged**
