### PR TITLE
Introduce a Unique ID tracking TestExecutionListener

### PR DESCRIPTION
**Pull request by sbrannen**
## Overview

This is a draft PR for #2619.

The feature should be functionally complete.

This PR is "draft" status for review of the feature in general but more importantly to gain consensus on the names of the system properties that are used to configure the listener.

Documentation will be added once there is consensus on the implementation and naming for the system properties.

All commits will be squashed prior to merging with an appropriate commit message.

---

### Definition of Done

- [x] There are no TODOs left in the code
- [x] Method [preconditions](https://junit.org/junit5/docs/snapshot/api/org.junit.platform.commons/org/junit/platform/commons/util/Preconditions.html) are checked and documented in the method's Javadoc
- [x] [Coding conventions](https://github.com/junit-team/junit5/blob/HEAD/CONTRIBUTING.md#coding-conventions) (e.g. for logging) have been followed
- [x] Change is covered by [automated tests](https://github.com/junit-team/junit5/blob/HEAD/CONTRIBUTING.md#tests) including corner cases, errors, and exception handling
- [x] Public API has [Javadoc](https://github.com/junit-team/junit5/blob/HEAD/CONTRIBUTING.md#javadoc) and [`@API` annotations](https://apiguardian-team.github.io/apiguardian/docs/current/api/org/apiguardian/api/API.html)
- [x] Change is documented in the [User Guide](https://junit.org/junit5/docs/snapshot/user-guide/) and [Release Notes](https://junit.org/junit5/docs/snapshot/user-guide/#release-notes)
- [x] All [continuous integration builds](https://github.com/junit-team/junit5#continuous-integration-builds) pass

### CODE REVIEW

**Comment by sbrannen** [comment]
@lazar-mitrovic and @sdeleuze, feel free to provide feedback on this PR.

**Comment by marcphilipp** [comment]
**Team decision:** The names of the system properties look good.

Another idea that came up was instead of using system properties directly, we should make the `ConfigurationParameters` available to listeners as part of the `TestPlan`. @sbrannen WDYT?

**Comment by sbrannen** [comment]
> **Team decision:** The names of the system properties look good.

Great. Thanks for reviewing them.

> Another idea that came up was instead of using system properties directly, we should make the `ConfigurationParameters` available to listeners as part of the `TestPlan`. @sbrannen WDYT?

Well, that was going to be a follow up PR, but I see that you all already came to the same conclusion. 😉 

I was thinking of either introducing a new default method in `TestExecutionListener` or introducing a new interface, something like `ConfigurationParametersConsumer` or `ConfigurationParametersAware` (inspired by similar interfaces from the Spring Framework).

The new method could be `void setConfigurationParameters(ConfigurationParameters)`.

**Comment by marcphilipp** [comment]
Why not make it part of the `TestPlan` since it has the same scope?

**Comment by sbrannen** [comment]
> Why not make it part of the `TestPlan` since it has the same scope?

Ahhhh.... you're proposing we simply introduce `ConfigurationParameters getConfigurationParameters()` in the `TestPlan` itself.

Yes, I think that's a better idea. 👍 

I created #2631 to address that.

**Comment by sbrannen** [comment]
This has been merged into `main` in a34d435f7bd2c8bbb5e30cc8ad72371df2404451.

**Pull request closed without merging**
